src/main/kotlin/demo.kt
src/main/kotlin/io/fritz2/binding/binding.kt
src/main/kotlin/io/fritz2/binding/mount.kt
src/main/kotlin/io/fritz2/binding/seq.kt
src/main/kotlin/io/fritz2/binding/var.kt
src/main/kotlin/io/fritz2/dom/dom.kt
src/main/kotlin/io/fritz2/dom/mount.kt

Seq and MultiMountPoint for DOM elements

Multimountpoint

---

core/src/main/kotlin/io/fritz2/binding/seq.kt
core/src/main/kotlin/io/fritz2/binding/subseq.kt
core/src/main/kotlin/io/fritz2/dom/tag.kt
examples/gettingstarted/src/main/kotlin/io/fritz2/examples/gettingstarted/gettingstarted.kt
examples/nestedmodel/src/main/kotlin/io/fritz2/examples/nestedmodel/nestedmodel.kt
examples/validation/src/main/kotlin/io/fritz2/examples/validation/validation.kt

Added a new Seq class for hiding `Flow<Patch<T>>`

added new Seq class

---

core/src/main/kotlin/io/fritz2/binding/validation.kt
core/src/main/kotlin/io/fritz2/dom/tag.kt
examples/nestedmodel/src/main/kotlin/io/fritz2/examples/nestedmodel/nestedmodel.kt
examples/validation/src/main/kotlin/io/fritz2/examples/validation/validation.kt
examples/validation/src/main/web/index.html
examples/validation/src/main/web/style.css

Added and fixed some stuff in validation.

Optimize validation

---

core/src/main/kotlin/io/fritz2/dom/html/html.kt

throw exception when tried to render multiple root tags

---

core/src/main/kotlin/io/fritz2/dom/html/elements.kt
examples/gettingstarted/src/main/kotlin/io/fritz2/examples/gettingstarted/gettingstarted.kt
examples/todomvc/src/main/kotlin/io/fritz2/examples/todomvc/todomvc.kt

this can easily be done for all parameters that are static be definition...

Label for as parameter

---

core/src/main/kotlin/io/fritz2/remote/remote.kt
core/src/test/kotlin/io/fritz2/remote/remote.kt
examples/remote/src/main/kotlin/io/fritz2/examples/remote/remote.kt

please review my idea for the content-type header field

reworked and extend remote api

---

core/src/commonMain/kotlin/dev/fritz2/identification/modelid.kt

renaming classes in modelid.kt

---

core/src/jsMain/kotlin/dev/fritz2/dom/text.kt
core/src/jsTest/kotlin/dev/fritz2/binding/events.kt
core/src/jsTest/kotlin/dev/fritz2/binding/seq.kt
core/src/jsTest/kotlin/dev/fritz2/binding/store.kt
core/src/jsTest/kotlin/dev/fritz2/binding/text.kt
core/src/jsTest/kotlin/dev/fritz2/dom/attributes.kt
core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt
core/src/jsTest/kotlin/dev/fritz2/dom/tag.kt
core/src/jsTest/kotlin/dev/fritz2/dom/text.kt
core/src/jsTest/kotlin/dev/fritz2/routing/routing.kt
core/src/jsTest/kotlin/dev/fritz2/test/utils.kt

added-short-text-method

---

lenses-annotation-processor/build.gradle.kts

Fixed kotlin block in build.gradle.kts

---

build.gradle.kts
core/src/jsMain/kotlin/dev/fritz2/dom/comment.kt
core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsTest/kotlin/dev/fritz2/dom/comment.kt
lenses-annotation-processor/build.gradle.kts

Added comment functionality

---

core/src/jsMain/kotlin/dev/fritz2/dom/mount.kt
core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsMain/kotlin/dev/fritz2/dom/text.kt
core/src/jsTest/kotlin/dev/fritz2/binding/mount.kt

Fix mounting order

---

core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
core/src/jsTest/kotlin/dev/fritz2/binding/store.kt

renamed to handleAndOffer + added first test

---

.github/workflows/build.yml
core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt

Open tag classes for inheritance

---

core/src/jsMain/kotlin/dev/fritz2/remote/remote.kt
core/src/jsTest/kotlin/dev/fritz2/remote/remote.kt

Added new append() function and added a new test which uses crudcrud.com

Extending remote extension

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
build.gradle.kts
core/build.gradle.kts
lenses-annotation-processor/build.gradle.kts

Publishing of snapshots to oss.jfrog.org

---

core/src/jsMain/kotlin/dev/fritz2/dom/attributes.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
core/src/jsMain/kotlin/dev/fritz2/dom/mount.kt
core/src/jsTest/kotlin/dev/fritz2/dom/html/mount.kt

Add missing SelectedAttribteDelegate

---

.github/workflows/publish.yml
.github/workflows/release.yml

fixed with publishing bug in gh-actions

Fixed problem with gh-actions

---

core/src/jsMain/kotlin/dev/fritz2/dom/html/render.kt
core/src/jsTest/kotlin/dev/fritz2/dom/html/render.kt

Added new render func + added missing kdoc

New render convenience function

---

core/src/jsMain/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
core/src/jsMain/kotlin/dev/fritz2/repositories/repositories.kt
core/src/jsMain/kotlin/dev/fritz2/repositories/rest/rest.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/rest/rest.kt

added new addOrUpdate method to QueryRepository + update tests

New addOrUpdate method in QueryRepository

---

core/src/jvmMain/kotlin/dev/fritz2/validation/validation.kt

added msgs attribute to jvm Validator implementation

Added msgs attribute for jvm target

---

core/src/jsMain/kotlin/dev/fritz2/remote/remote.kt

#167: No trailing slash in remote

---

components/src/jsMain/kotlin/app.kt
core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsMain/kotlin/dev/fritz2/remote/remote.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/alignment.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/background.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/border.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/color.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/flexbox.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/gridLayout.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/layout.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/position.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/shadow.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/space.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/typography.kt

- changed URLs to point at the *english* version of MDN. This primarely affects the fritz2 styling subproject.
- corrected internal links to renewed package structure
- corrected small typos

Correct API documentation

---

core/src/jsMain/kotlin/dev/fritz2/binding/action.kt
core/src/jsMain/kotlin/dev/fritz2/binding/mount.kt
core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
core/src/jsMain/kotlin/dev/fritz2/history/history.kt

create new coroutine scope for each handler

---

kitchenSink/src/jsMain/kotlin/flexBoxDemo.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt

added wide sizes

---

datatable/build.gradle.kts
datatable/src/jsMain/kotlin/dev/fritz2/components/table.kt
datatable/src/jsMain/resources/index.html
kitchenSink/src/commonMain/kotlin/model/tableStore.kt
kitchenSink/src/jsMain/kotlin/app.kt
kitchenSink/src/jsMain/kotlin/tableDemo.kt
settings.gradle.kts

- table component is now available as draft within its own subproject ``datatable``
- table demo added to kitchenSink

Add table component via subproject

---

core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt

Added URL encoding/decoding for StringRoute.

Fixed URL escaping in StringRouter

---

kitchenSink/src/jsMain/kotlin/inputDemo.kt

Updated page to agreed formats.
Other notes:
I used the simpleLinkWithBackground from app.kt for midtext links to other components. That style should be re-worked by Moritz.
Added notes about form control (using labels and validation). 
Added a few input type examples.

updated input demo

---

components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
kitchenSink/src/jsMain/kotlin/checkboxesDemo.kt
kitchenSink/src/jsMain/kotlin/radioDemo.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt

- radioDemo, checkboxesDemo reworking
- creating focus color property

- checkbox, radio, switch style and component reworking

---

kitchenSink/src/jsMain/kotlin/app.kt
kitchenSink/src/jsMain/kotlin/tooltipDemo.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt

tooltip showcase

---

core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
core/src/jsTest/kotlin/dev/fritz2/validation/validation.kt

Added find & filter methods to `Validator` on js side.

Added convenience methods for Validator

---

styling/src/jsMain/kotlin/dev.fritz2.styling/theme/theme.kt

- adopt recent changes of the ``render`` functions from PR#233 to the theme wrapping ones in styling sub-project

Harmonize theme wrapping render functions

---

components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/select.kt

Added formControl support for: selectField, switch, textArea

---

components/src/jsMain/kotlin/dev/fritz2/components/global.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt

Fix placement of modals

---

components/src/jsMain/kotlin/dev/fritz2/components/input.kt
components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
components/src/jsMain/kotlin/dev/fritz2/components/select.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt

This branch introduces 6 shades of gray to the theme colors, replacing light and lightEffect with lightGray and lighterGray and adding 4 more shades of gray.

shadesOfGray

---

styling/src/jsMain/kotlin/dev.fritz2.styling/params/typography.kt

added "fontFamilyKey" to typography.kt and set usage in fontFamily property

fontFamily

---

components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt

- Fix Issue #259
- rework API for extending, overriding and customizing a renderer for the formControl component.

Repairs API for extending formControl

---

components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
components/src/jsMain/kotlin/dev/fritz2/components/input.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/select.kt
components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt

- removed required property
- open formControl to be extended by new wrapping functions and renderers
- correct some typo in basic abstraction

Improve API of formControl

---

components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
components/src/jsMain/kotlin/dev/fritz2/components/stack.kt

Add missing event contexts

---

core/src/jsMain/kotlin/dev/fritz2/lenses/lens.kt
core/src/jsTest/kotlin/dev/fritz2/lenses/lens.kt

Added function for creating `Lens`es of `String` for different kotlin basic types

Added convenience functions for Lenses

---

components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt

Added default parameters and optimize imports

Small improvements for formControl

---

README.md

Let's celebrate your successful migration to BOTH-mode/IR 🎉
(https://kotlinlang.slack.com/archives/C0B8L3U69/p1614260289050200)

Add Kotlin/JS IR badge to README

---

core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt

renamed Router functions from marshal -> serialize

Small refactoring for Router

---

core/src/jsMain/kotlin/dev/fritz2/history/history.kt
core/src/jsMain/kotlin/dev/fritz2/tracking/tracking.kt
core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
core/src/jsTest/kotlin/dev/fritz2/history/history.kt
core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
core/src/jsTest/kotlin/dev/fritz2/validation/validation.kt

Streamlined API of Router, Validator, History and Tracker.

Streamlining API

---

README.md
lenses-annotation-processor/build.gradle.kts

Using offical Slack badge

---

components/src/jsMain/kotlin/dev/fritz2/components/input.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt

moves basicInputStyles of inputFieldComponent to default theme.

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
components/src/jsMain/kotlin/dev/fritz2/components/box.kt
components/src/jsMain/kotlin/dev/fritz2/components/button.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/file.kt
components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
components/src/jsMain/kotlin/dev/fritz2/components/input.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/select.kt
components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
components/src/jsMain/kotlin/dev/fritz2/components/stack.kt
components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsTest/kotlin/dev/fritz2/dom/tag.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/layout.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/params.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/styledElements.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/style.kt

Rework of `StylingClass`

---

core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt

Example code:
```kotlin
input {
placeholder("Press enter to set")
value(store.data)
keyups.enter() handledBy store.update
}
```

New convenience functions for getting current value on enter (Input & TextArea)

---

styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt

More info here: https://www.w3schools.com/cssref/css_websafe_fonts.asp

Using websafe fonts in default theme

---

components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt

Added missing resizeBehavior option `both`

---

components/src/jsMain/kotlin/dev/fritz2/components/select.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt

moves basicStyles of selectField and textArea to defaultTheme, adds variant to textArea

moves basicStyles of selectField and textArea to defaultTheme

---

components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt

- remove ``title`` from header-section
- add some API documentation
- adjust``colors.tertiary`` to brighter grays so they fit as good choices for data items backgrounds like in the DataTable
- change hovering effect of DataTable to horizontal borders instead fo changing colors

Polish DataTable

---

components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt

Rework new `Svg` tag in core

---

publishing.gradle.kts

Fixed the links & name and added println

Improve & fix `publishing.gradle.kts`

---

core/src/commonMain/kotlin/dev/fritz2/identification/inspector.kt
core/src/commonTest/kotlin/dev/fritz2/identification/inspector.kt

This new methods simplifies the use of `Inspector` with data of type `List<T>`

Added convenience methods `inspectEach()` for `Inspector`

---

components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
components/src/jsMain/kotlin/dev/fritz2/components/menu.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt

This PR adds the `MenuComponent` from the incubator.
~There are still some adjustments to be made since the way buttons are styled has changed since the menu was developed.~
Closes #339 .

Add MenuComponent

---

README.md
build.gradle.kts
components/build.gradle.kts
components/src/jsMain/kotlin/dev/fritz2/components/file.kt
core/build.gradle.kts
core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsMain/kotlin/dev/fritz2/dom/window.kt
core/src/jsMain/kotlin/dev/fritz2/remote/websocket.kt
core/src/jsMain/kotlin/dev/fritz2/webcomponents/webcomponents.kt
core/src/jsTest/kotlin/dev/fritz2/utils/myer.kt
gradle.properties
gradle/wrapper/gradle-wrapper.properties
lenses-annotation-processor/build.gradle.kts
lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lenses/LensesAnnotationProcessor.kt
lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lenses/LensesAnnotationProcessorTests.kt
settings.gradle.kts
styling/build.gradle.kts
styling/src/jsMain/kotlin/dev/fritz2/styling/style.kt
test-server/build.gradle.kts

Using Kotlin 1.5 version and updated dependencies to latest version.
Fixes #389

Upgrade to Kotlin 1.5

---

core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
core/src/jvmMain/kotlin/dev/fritz2/validation/validation.kt

```kotlin
val save = handleAndEmit<Person> { person ->
// only update the list when new person is valid
if (validator.isValid(person, "add")) {
emit(person)
validator.reset()
Person()
} else person
}
```
Fixes  #432

Added new `reset()` function to `Validator`

---

components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt

* remove unnecessary `getElementById()` call
* fix `id` and `prefix` placement in DOM (analog to `dropdown`)
* fix and rearrange kdoc
* refactor & reformat code
Fixes #391

Rework `popover` component

---

core/src/jsMain/kotlin/dev/fritz2/dom/events.kt

Handle possible CastException

---

components/src/jsMain/kotlin/dev/fritz2/components/menu/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/menu/context.kt

 Expose open/close handlers or an external store for submenu component

---

core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt

added missing convenience method to eventlistener at fieldset

fix baseClass at Svg and Path

---

core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt

offer convenience method to merge the flows of two DomListeners

merge multiple DomListener

---

core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt

Just a left-over from development. Do not add this to release note...

Remove unwanted log from Tag/className

---

README.md
components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt
core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
core/src/jsTest/kotlin/dev/fritz2/dom/html/events.kt
core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt

Do not include this into the release notes!
Simply add a remark to PR 556 section, that the final result relies on this PR too.

Polish Shortcut API

---

README.md

not relevant for release notes

Improve Badges

---

core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
www/src/pages/blog.njk
www/src/pages/recipes/Recipes.md

* removed not needed `syncBy` and moved `syncWith` to `WithJob` interface
* added new Recipe section at webpage

fritz2 API cleanup

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/disclosure.kt
www/package-lock.json
www/package.json
www/src/_includes/layouts/docs.njk
www/src/_includes/layouts/docsWithContentNav.njk
www/src/_includes/layouts/headlessWithContentNav.njk
www/src/_includes/layouts/post.njk
www/src/pages/docs/Getting Started.md
www/src/styles/main.css
www/tailwind.config.js

use tailwind-typography for www

---

README.md
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
www/src/blog/posts/paradigm-shift-for-components.md
www/src/pages/docs/10_Getting Started.md
www/src/pages/docs/60_Http.md
www/src/pages/headless/dataCollection.md

Not relevant for release notes!

Small API and Documentation corrections for RC1

---

headless-demo/.github/workflows/playwright.yml
headless-demo/.gitignore
headless-demo/package-lock.json
headless-demo/package.json
headless-demo/playwright.config.ts
headless-demo/tests/listbox.spec.ts

- add playwright to demo project
- add first test-suite (listbox)
There is currently no integration into the build process, besides a github task, if headless-demo modul is pushed to master. We need to discuss, whether we need more automatic integration in the future or not.
As we will not change constantly the behaviour of headless components, it might be sufficient, if the developer and the reviewer start the tests manually on development or during review process locally.

Set up initial playwright infrastructure

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/dataCollection.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/menu.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/tooltip.kt

In order to ease up automatic testing,...
- ... IDs are added to some components and bricks
- ... some atrificial state attributes are added to some tags to make the internal state like selection, active or disabled explicitly available

Improve headless demos for automatic UI testing

---

headless-demo/tests/README.md
www/README.md
www/src/pages/headless/checkboxGroup.md
www/src/pages/headless/disclosure.md
www/src/pages/headless/textArea.md

- Add information and design guide to headless ui tests
- Reduce 11ty readme to the needed aspects
- add information to use 11ty on Windows to readme
- add information for keyboard interaction to some headless components
- remove some false information about keyboard handling for textarea component
Do not include this into release notes!

Improve the documentation with small additions and changes

---

.github/workflows/release.yml

Duplicate www.yml workflow code for publishing website assets

Fix release.yml workflow

---

www/src/pages/docs/30_State Management.md

Fix the docs for calling a Handler directly

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt

Fix for Attribute referenced id:
- switchWithLabel
- radioGroup
- checkboxGroup

Fix for Attribute referenced id

---

core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/mount.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt

Change the receiver of the `content` lambda in `render` from `RenderContext`to `Tag<*>`

Make render's lambda run on Tag instead of RenderContext

---

core/src/commonMain/kotlin/dev/fritz2/core/lens.kt

Improve index-based `lensOf` function

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt

Fix ModalPanel id being overridden

---

README.md
www/src/pages/docs/20_Render HTML.md
www/src/pages/docs/30_State Management.md
www/src/pages/docs/40_Validation.md
www/src/pages/docs/90_Web Components.md

Rework docs for Webcomponents

---

www/src/pages/docs/60_Http.md

Improve http example

---

www/src/pages/docs/30_State Management.md

Add documentation about unsafe tracking functions

---

www/src/pages/docs/20_Render HTML.md
www/src/pages/recipes/Recipes.md.bak

Document how to set initial attribute values immediately

---

headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/aria.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/attributes.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/hooks.kt
headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/hooks.kt

Resolve bug with alsoExpression on Hook with Flow

---

build.gradle.kts
core/build.gradle.kts
core/karma.config.d/custom.browser.js
test-server/build.gradle.kts
test-server/src/main/kotlin/dev/fritz2/Server.kt
test-server/src/main/resources/application.conf

* Fix CORS errors when doing HTTP request in Karma's chrome-headless browser against the Ktor `test-server` API by setting the `--disable-web-security` flag when using chrome-headless browser.
* Update Ktor to the latest version `2.2.2` in `test-server` module

Fix CORS problems in JS-tests when requesting the `test-server` API

---

snippets/src/jsMain/kotlin/dev/fritz2/examplesdemo/fundamentals.kt
www/src/pages/docs/20_Fundamentals.md
www/src/pages/docs/30_Render HTML.md

Adapt included example to final fundamental's example.

Adapt included example to final fundamental's example.

---

core/src/jsMain/kotlin/dev/fritz2/core/attributes.kt

Removes the wrong working `text` attribute extension functions

Removes the wrong working `text` attribute extension functions

---

gradle.properties

enable gradle caching and deamon to speed up (incremental) builds
@haukesomm : please test on windows and review
@jamowei : please test on linux and review
@chausknecht : please test on mac and review

Improve gradle-settings

---

build.gradle.kts
www/src/pages/docs/10_Getting Started.md
www/src/pages/docs/30_Render HTML.md

Add some information at https://www.fritz2.dev/docs/render/#style-and-enrich-your-ui-with-attributes
fixes #745

Add some explicit information for dealing with CSS

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
www/src/pages/docs/10_Getting Started.md
www/src/pages/headless/dataCollection.md

- DataCollection typo
- Phrasing of section "Create A Project".

Docs mini fixes

---

core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt

These are a few utilities I end up using over and over in my projects. For example, if I have nullable fields, the following is a bit cumbersome:
```kotlin
thing.data.render { t ->
if (t != null) { 
// ... keep going ...
}
}
```
hence the utility for
```kotlin
thing.data.renderIfNotNull { t ->
// ... keep going ...
}
```
The same happens for empty lists, where one usually needs to consider the empty list case differently (for example, showing _No results found_), but which right now requires nested `render`. My suggestion would turn this into:
```kotlin
results.data.renderEachIfNotEmpty(
otherwise = { + "No results" }
) {
// render one element
}
```

Utility functions for `RenderContext`

---

www/src/pages/docs/100_Web Components.md
www/src/pages/docs/200_ToDos.md.bak
www/src/pages/docs/20_Fundamentals.md
www/src/pages/docs/30_Render HTML.md
www/src/pages/docs/40_StoreCreation.md
www/src/pages/docs/50_StoreMapping.md
www/src/pages/docs/60_Routing.md
www/src/pages/docs/70_Validation.md
www/src/pages/docs/80_Http.md
www/src/pages/docs/90_Websockets.md

- Parts 00 - 30 have minor changes
- Part 50 needs Reviewer's attention because I changed the order of the Lens docs
- Parts 40-100 received an english text overhaul
- Changed the document order number for the www structure according to the filenames (2 were wrong)
- Removed entries from todo file which were already done

English Overhaul of Documentation

---

www/src/pages/docs/20_Fundamentals.md

Explains the use of backticks in a fundamental example.

Remove and fix some TODO in docs

---

headless-demo/package-lock.json
headless-demo/package.json
headless-demo/playwright.config.ts
headless-demo/tests/components/checkbox.spec.ts
headless-demo/tests/components/datacollection.datatable.spec.ts
headless-demo/tests/components/datacollection.gridlist.spec.ts
headless-demo/tests/components/disclosure.spec.ts
headless-demo/tests/components/inputfield.spec.ts
headless-demo/tests/components/listbox.spec.ts
headless-demo/tests/components/menu.spec.ts
headless-demo/tests/components/modal.spec.ts
headless-demo/tests/components/popover.spec.ts
headless-demo/tests/components/radio.spec.ts
headless-demo/tests/components/switch.spec.ts
headless-demo/tests/components/tabgroup.spec.ts
headless-demo/tests/components/textarea.spec.ts
headless-demo/tests/components/toast.spec.ts
headless-demo/tests/components/tooltip.spec.ts

- update to current playwright version and remove obsolete dependencies
- try to improve failing tests (still some are flaky, especially those of datatable or gridlist)
- improve configuration to run more tests in parallel
- try to remove unnecessary delays and improve locators

Improve UI-Testing

---

www/src/pages/docs/20_Fundamentals.md

Fix small doc issues after adding store lifecycles

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/www.yml
headless-demo/README.playwright.md
headless-demo/playwright.config.ts
www/.eleventy.js
www/README.md

Fixes issues with the build:
https://github.com/jwstegemann/fritz2/actions/runs/6850719423/job/18625447145

Change to new distribution location from Kotlin 1.9

---

core/build.gradle.kts
examples/masterdetail/build.gradle.kts
examples/validation/build.gradle.kts
headless/build.gradle.kts
lenses-annotation-processor/build.gradle.kts
serialization/build.gradle.kts
test-server/build.gradle.kts
versions.properties

https://splitties.github.io/refreshVersions/

Improve dependency management by using `refreshVersions`

---

www/src/pages/docs/20_Fundamentals.md
www/src/pages/docs/30_Render HTML.md
www/src/pages/docs/40_StoreCreation.md
www/src/pages/headless/listbox.md
www/src/pages/headless/menu.md
www/src/pages/headless/modal.md
www/src/pages/headless/popOver.md
www/src/pages/headless/toast.md
www/src/pages/headless/tooltip.md

Looked mostly at the newly added sections concerning the creation and cancellation of jobs in render contexts and stores.

Review documentation-changes after PR #806.

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt

see https://github.com/jwstegemann/fritz2/pull/830

do not use flatMapLatest for events

---

www/src/pages/docs/40_StoreCreation.md

Add documentation for `Store`s `current` property.

Add documentation for `Store`s `current` property

---

headless-demo/tests/components/datacollection.datatable.spec.ts
headless-demo/tests/components/datacollection.gridlist.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/scrollintoview/scrollintoview.kt
kotlin-js-store/yarn.lock
versions.properties

- Upgrades versions to newest
- Adapts and improves two tests due to better performing new  `scroll-into-view-if-needed`-version

Refresh Versions for upcoming RC13 Release

---

core/build.gradle.kts
headless/build.gradle.kts
lenses-annotation-processor/build.gradle.kts
publishing.gradle.kts
serialization/build.gradle.kts

Fix implicit dependency error in Gradle for publishing

---

core/build.gradle.kts
examples/gettingstarted/build.gradle.kts
examples/masterdetail/build.gradle.kts
examples/nestedmodel/build.gradle.kts
examples/performance/build.gradle.kts
examples/remote/build.gradle.kts
examples/routing/build.gradle.kts
examples/tictactoe/build.gradle.kts
examples/todomvc/build.gradle.kts
examples/validation/build.gradle.kts
examples/webcomponent/build.gradle.kts
headless-demo/build.gradle.kts
headless/build.gradle.kts
lenses-annotation-processor/build.gradle.kts
serialization/build.gradle.kts
snippets/build.gradle.kts
www/src/pages/docs/10_Getting Started.md
www/src/pages/headless/headlessComponents.md

More info [here](https://kotlinlang.org/docs/multiplatform-hierarchy.html#default-hierarchy-template)

Use Kotlin default hierarchy template

---

www/src/pages/docs/45_EventHandling.md

Fixes minor issues in doc

---

www/src/pages/docs/30_Render HTML.md

Add documentation for `joinClasses`-function

---

www/.eleventy.js
www/src/index.njk

Update footer to use dynamic year

---

www/src/pages/docs/50_StoreMapping.md

Fixes small styling issue in sealed hierarchy example
Does not need to appear in the release notes!

Fixes small styling issue in sealed hierarchy example

---

examples/todomvc/src/jsMain/resources/index.html
www/src/blog/posts/paradigm-shift-for-components.md
www/src/pages/docs/45_EventHandling.md

Commit fdbf998ac23026658c37a5e37610648642ed1592 renamed bunch of Java files. This PR adjusts sources to changes.

Update broken references

---

headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/floatingui/core/Types.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/floatingui/utils/Types.kt

Suppresses unused warning for floating-ui type definitions
