jwstegemann/fritz2

core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt

uses now Map<String, String> cause type information on type Any (like it was before) getting lost...
**Important**: When merging this PR the routing example must be adjusted!

Fixed MapRouter

---

.github/workflows/build.yml
core/src/jsMain/kotlin/dev/fritz2/dom/attributes.kt
core/src/jsMain/kotlin/dev/fritz2/dom/mount.kt
core/src/jsTest/kotlin/dev/fritz2/dom/attributes.kt

Adds a single mount point for boolean attributes (flags) which is flexible enough to fulfill the following requirements:
1. Add an attribute (with an empty value), when the flow emits `true`, remove the attribute, when the flow emits `false`:
```kotlin
val flow: Flow<Boolean> = ...
render {
div {
flow.bindAttr("hidden")
}
}
```
will lead to 
```html
<div hidden/>
```
when `flow` emits `true` and 
```html
<div/>
```
when `flow` emits `false`.
1. Map the boolean value to an arbitrary string:
```kotlin
val flow: Flow<Boolean> = ...
render {
a {
flow.bindAttr("aria-expanded", removeWhenFalse = false) {
it.toString()
}
}
}
```
will lead to 
```html
<a aria-expanded="true"/>
```
when `flow` emits `true` and 
```html
<a aria-expanded="false"/>
```
when `flow` emits `false`.
1. A combination of 1 …

Add single mount point for boolean attributes

---

README.md

The URL to the project setup documentation seemed to have changed.

correct link to documentation

---

core/src/jsMain/kotlin/dev/fritz2/dom/attributes.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt

Fixes #171 
This PR modifies all boolean attributed in `core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt`. This assumes that all boolean attributes work the same way: When `true` the attribute is set, when `false` the attribute is removed.

#171: Fix boolean attribute delegates

---

components/src/jsMain/kotlin/dev/fritz2/components/box.kt
components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
components/src/jsMain/kotlin/dev/fritz2/components/input.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
components/src/jsMain/kotlin/dev/fritz2/components/stack.kt
components/src/jsMain/kotlin/dev/fritz2/components/styledElements.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/alignment.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/flexbox.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/gridLayout.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/params/layout.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/theme.kt

- fix some links for KDoc
- remove syntax of some links, because KDoc is not able to resolve those. Apparently this affects all links from one submodule to another. Could be reworked after an upgrade to a newer version of dokka! Links are now marked with double back ticks for detecting and repairing them later on.

Fix unrecognized apidoc links

---

components/build.gradle.kts
datatable/build.gradle.kts
kitchenSink/build.gradle.kts
styling/build.gradle.kts

When adding compontens lib to your gradle build file you get core, styling and components also.

Makeing dependencies transitive

---

core/src/jsMain/kotlin/dev/fritz2/binding/mount.kt
core/src/jsMain/kotlin/dev/fritz2/dom/mount.kt
core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsMain/kotlin/dev/fritz2/utils/myer.kt
core/src/jsTest/kotlin/dev/fritz2/utils/myer.kt

- patches within Myer's diff algorithm are now delivered as ``List`` and not as ``Flow`` anymore.
- obviously the browser's rendering engine are optimized to apply bigger DOM changes at once, so the overall rendering speed is much faster now.

Optimize patch handling

---

components/src/jsMain/kotlin/dev/fritz2/components/button.kt
components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
components/src/jsMain/kotlin/dev/fritz2/components/stack.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt

- fixes #227
- remove ``RenderContext`` as receiver
- add specific Tag as receiver or ``Tag<HtmlElement>`` for _generic_ cases

Remove RenderContext as Receiver

---

core/src/commonMain/kotlin/dev/fritz2/resource/resource.kt
core/src/commonMain/kotlin/dev/fritz2/serialization/serializer.kt
core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
core/src/jsMain/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
core/src/jsMain/kotlin/dev/fritz2/repositories/repositories.kt
core/src/jsMain/kotlin/dev/fritz2/repositories/rest/rest.kt
core/src/jsMain/kotlin/dev/fritz2/utils/myer.kt
core/src/jsTest/kotlin/dev/fritz2/remote/websocket.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/rest/rest.kt

Refactor repositories API

---

components/src/jsMain/kotlin/dev/fritz2/components/validation/validation.kt

Replaced throwing `RootStoreHasNoValidator` exception with returning null instead.

Removed `RootStoreHasNoValidator` exception fom ComponentValidation

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt

This PR makes the `AlertComponent` change it's icon based on the specified alert-severity.
The icon can still be overridden via the `icon`-property of `AlertComponent`.

Change alert-icon based on the specified alert-severity

---

components/src/jsMain/kotlin/dev/fritz2/components/button.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
components/src/jsMain/kotlin/dev/fritz2/components/input.kt
components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt

- element property will be applied with the bigger priority than all other component exposed props. Example: ``type`` property of ``inputField`` can be set to ``password`` but within element's context to ``text``, so ``text`` _wins_.

Rework element property prioritization

---

components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt

This PR fixes the AppFrame not expanding to full vertical height on Firefox.
This behavior affects Firefox on all operating systems.

Fix AppFrame height on Firefox

---

core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt

I ran into this when trying to capture the input events that the input slider fires ias you drag it. It fires a change event when you stop dragging. Likewise, useful on text input to capture values as you type.
I modified the test to test both events.

support values and valuesAsNumber on input events as well

---

components/src/jsMain/kotlin/dev/fritz2/components/select.kt

Setting default with to 100% instead of 50%. 
I have also tested in kitchensink and it looks good.

Fixed default styling of `selectField`

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
components/src/jsMain/kotlin/dev/fritz2/components/button.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/file.kt
components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
components/src/jsMain/kotlin/dev/fritz2/components/input.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/select.kt
components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
components/src/jsMain/kotlin/dev/fritz2/components/stack.kt
components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
components/src/jsMain/kotlin/dev/fritz2/components/toast.kt

- add central ``Component<T>`` interface for unifying the component's
rendering process. This also reduces the code of the corresponding
factory methods. Together it enhances also the extensibility of
all components!
- refactor all components to implement this interface
- rework ``CloseButtonProperty`` and its mixin implementation in order
to make its interface and therefore the usage much cleaner
(no exposure of a handler anymore!)
- integrate the ``CloseButtonProperty`` changes within the using
components:
- modal
- popover
- toast
- ~~ATTENTION: ``file`` component still waiting for refactoring. Its
factory functions have different return types, which makes the
implementation a bit more daunting!~~
- remove obsolete convenience functions from ``alert`` component
- add api documentation …

Refactor internal component structure

---

components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
components/src/jsMain/kotlin/dev/fritz2/components/toast.kt

- add missing prefix to ``prefix`` property in order to avoid naming collisions
- improve custom styling by separating the default style from the custom styling and applying both
- add missing property to just change the icon

Improve CloseButton API

---

components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt

- specify receiver for ambiguous properties (same name in group and single component)
- ``label``, ``disabled`` and ``severity`` should work now for radioGroup and checkboxGroup

Fix some bugs in grouping form components

---

components/src/jsMain/kotlin/dev/fritz2/components/toast.kt

- The rendering sequence now depends on the basic placement: New toasts should always be stacked on existing ones, which naturally depends on the basic placement:
- top: the new toast must be rendered *below* the existing ones
- bottom: the new toast must be rendered *above* the existing ones (reverse order needed)

Harmonize toast behaviour

---

components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
core/src/jsMain/kotlin/dev/fritz2/binding/handlers.kt
core/src/jsTest/kotlin/dev/fritz2/binding/handlers.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/rest/rest.kt
core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
lenses-annotation-processor/build.gradle.kts

**Advantage**: No extra import is needed, which Intellij IDEA can't guess.
**Disadvantage**: No compiler error when using parameterless `invoke()` function for non-`Unit` handlers.
My experiments show that at runtime this not very bad, but of course it can be confusing. That is why I think we need to discuss this!?
```kotlin
store.handle { assertTrue(true); it }()
store.handle { assertTrue(true); it }(Unit)
store.handle<String> { n, s -> assertFalse(s::class == String::class); n }()
store.handle<String> { n, s -> assertTrue(s::class == Unit::class); n }()
store.handle<String> { n, s -> assertTrue(s.length == undefined); n }()
store.handle<String> { n, s -> assertTrue(s.substring(1) == undefined); n }()
store.handle<String> { n, _ -> assertTrue(true); n }("Hello")
```

Parameterless `invoke` function inside the Hander interface

---

styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt

Small visual fix in DefaultTheme by setting inputField padding to small when setting `small`
as size.

Visual fix of padding in small inputField

---

styling/src/jsMain/kotlin/dev.fritz2.styling/params/border.kt

This PR resolves issue #330 by swapping the implementations of `BorderContext.horizontal(...)` and `BorderContext.vertical(...)` so the borders created by them follow the semantics of the respective method names.
This means:
- `horizontal` now creates borders at the top and at the bottom of an element and
- `vertical` now creates borders to the left and right of an element
Currently it doesn't seem like there are any usages of these methods in fritz2 itself. The change should be stated in the release notes regardless since other projects might use these functions already and would need to adjust their code.

Fix horizontal and vertical convenience functions of BordersContext DSL

---

components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
components/src/jsMain/kotlin/dev/fritz2/components/input.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/select.kt
components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt

For a better readability and intelligibility the parameter **store** refactores to **value** or rather **values**.
**value** is intended for components with a ``Store<T>`` and **values** is intended for ``Store<List<T>>``.
**Until 0.9.x**
```kotlin
inputField(store = myStore) {}
checkboxGroup(store = myListStore, items = myItems) {}
```
**New**
```kotlin
inputField(value = myStore) {}
checkboxGroup(values = myListStore, items = myItems) {}
```
Especially the inputField and textArea get a better intelligibility .
**Until 0.9.x**
```kotlin
inputField(store = myStore) {} // Store variant
inputField { value(myFlow) } // Flow variant
```
**New**
```kotlin
inputField(value= myStore) {} // Store variant
inputField { value(myFlow) } // Flow variant
```

Harmonize parameter name in components with stores

---

components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/style.kt

This PR extends the `staticStyle` documentation to suggest using `style` whenever possible.
`staticStyle` should mainly be used internally (e.g. for component development) but can not actually be made `internal` as it needs to be accessible from the `components` package.
This PR also changes existing usages of `staticStyle` to `style` if needed.
Closes #303 .

Make `staticStyle` internal

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
components/src/jsMain/kotlin/dev/fritz2/components/button.kt
components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
components/src/jsMain/kotlin/dev/fritz2/components/select.kt
components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt
styling/src/jsMain/kotlin/dev.fritz2.styling/utils.kt

Based on issue https://github.com/jwstegemann/fritz2/issues/315 
The colors `info` , `success`, `warning`, `danger` and `neutral` changed to `ColorScheme` 
The property `color` of our `button` component refactors to `type` and based on the `colorScheme` approach now.
Our default theme deliveres following predefinitions: `primary`, `secondary`, `info`,  `success`, `warning`, `danger` but you can to use an other `ColorScheme`. Button without a type uses the `primary` ColorScheme.
`ColorScheme` got a function named `inverted()` it returns a `ColorScheme` which switches base with highlight and baseContrast with highlightContrast. A default use case can be if you want to create easily an inverted theme.
```kotlin
// old color configuration
clickButton {
text("danger")
color { danger }
}
// new …
```

Extends of ColorScheme approach

---

styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt

Move backgroundColor and fontColor from the `Theme` interface to the `Colors` interface.
Example:
```kotlin
// before
Theme().fontColor
Theme().backgroundColor
// now
Theme().colors.font
Theme().colors.background
// or in color styling DSL
{  
background {
color {
font //or background
}
}
}
```
Fixes #347

Move background & font colors to `Colors` interface

---

components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt

It is now possible to pass an external selection store into a DataTable **and** additionally wire selection events within the DataTable's ``events`` context.
```kotlin
dataTable(
rows = ..., rowIdProvider = ..., selection = someStore
) {
events {
// this events will now be handled *even though*
// a selection store is passed via factory function!
selectedRow handledBy someOtherStore.handler
selectedRow handledBy evenAnotherStore.handler
// ... and so on
}
columns {
// ...
}
}
```
Fixes #382

Fix selection forwarding to external store for DataTable component

---

styling/src/jsMain/kotlin/dev/fritz2/styling/params/alignment.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/params/background.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/params/border.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/params/params.kt

The `color` of `BackgroundContext` and `style` of `BorderContext` works now with media breakpoints
solved: #342

Fixes for using media breakpoints

---

components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt

Fixed css errors like `Failed to parse the rule '.@media (max-width: 48em){left:0!important;opacity:1!important;}'` in `appFrame` component

Fix css error in `appFrame` component

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt

This PR enables both custom styling and customization of the underlying `AlertComponent` for `ComponentValidationMessage.asAlert()`.
---
1. The property to adapt the size has changed from ``sizes`` to simply ``size`` to be compliant with the rest of the components! (see issue #412)
2. **This change is API-breaking only if`asAlert()` is called manually in your code.** In most cases this should not be the case as it is mainly used internally by the `ComponentValidationMessage`.
The method signature of `ComponentValidationMessage.asAlert()` has changed from
```kotlin
fun ComponentValidationMessage.asAlert(
renderContext: RenderContext,
size: FormSizes.() -> Style<BasicParams> = { normal },
stacking: AlertStacking.() -> Style<BasicParams> = { separated }
)
```
to
```kotlin
fun …
```

Improve `ComponentValidationMessage.asAlert()`

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
components/src/jsMain/kotlin/dev/fritz2/components/file.kt
components/src/jsMain/kotlin/dev/fritz2/components/pushButton.kt

This API change for `pushButton`, `clickButton` and `linkButton` harmonizes the way for setting an icon to it.
```kotlin
// before
pushButton {
type { info }
icon { fromTheme { circleInformation } }
text("Info")
}
// now
pushButton {
type { info }
icon { circleInformation }
text("Info")
}
```
In most cases it is enough to remove the `fromTheme()` function.
Fixes #392

Using `ComponentProperty` for setting an `IconDefinition` for a button

---

core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt

Fixes the following code example:
```kotlin
input {
value(store.data)
// not compiling, because of returning Listener instead of DomListener after using preventDefault()
changes.preventDefault().values() handledBy store.update
}
```

Fixed self type loss after using global functions on `Listener` like `preventDefault` etc.

---

core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt

We had some duplicated standard html elements in the API which causing troubles.
Example at `details` element:
```kotlin
// proper function
fun details(baseClass: String? = null, id: String? = null, content: Details.() -> Unit): Details =
register(Details(id, baseClass, job), content)
// duplicate which must be removed
fun details(baseClass: String? = null, id: String? = null, content: TextElement.() -> Unit): TextElement =
register(TextElement("details", id, baseClass, job), content)
```

Removed duplicated html elements which causing errors

---

components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/managed.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt

Components which need a z-index an their default values defined in `DefaultTheme`:
```
tableHeader (10)
tooltip (100)
dropdown (200)
popover (300)
appFrame (1000)
navbar (1000) -- will be replaced by appFrame
toast (2000)
modal (3000)
```
Fixes #395 and fixes #371

Use constant values for z-indices in components

---

components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt

- add new  general concepts for the *orientation* aspect of a component: That is align its item(s) in an *horizontal* or *vertical* way.
- offer a new mixin ``OrientationMixin`` for components
- add this mixin for the following components:
- Slider (no API change!)
- CheckBoxGroup: new ``orientation`` API, old ``direction`` marked as deprecated
- RadioGroup: new ``orientation`` API, old ``direction`` marked as deprecated
- ``direction`` → ``orientation``
- ``row`` → ``horizontal``
- ``column`` → ``vertical``
```kotlin
// old one with deprecation warning as:
// 'direction: ComponentProperty<CheckboxGroupComponent.DirectionContext.() -> CheckboxGroupComponent.Direction>' is deprecated. Use ``orientation`` instead
// 'row: CheckboxGroupComponent.Direction' is deprecated. Use ``orientation { …
```

Harmonize orientation settings

---

components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
components/src/jsMain/kotlin/dev/fritz2/components/menu.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

This PR reworks some parts of the menu- and dropdown-components based on feedback.
Changes:

Improve Menu- and DropdownComponent

---

core/src/jsMain/kotlin/dev/fritz2/tracking/tracking.kt
core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt

Currently the tracker does expect safe operations in order to work, so the client has to make shure, that no exception is beeing thrown by the passed operation.
This is quite dangerous, as the tracker will not stop working by itself (and there would be the need for a kind of _reset_ handler to be called when dealing with the exception).
This example should work now: The tracker will be stopped, but the exception is not swallowed and could be handled appropriately where needed:
```kotlin
val fooStore = object : RootStore<Int>(0) {
val t = tracker()
val h = handle {
t.track {
// unsafe operation is passed to ``track``
delay(500)
throw Exception("Boom!")
it + 1 // will never be reached
}
}
}
```
fixes #425

Make track safe for unsafe operations

---

components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt

This PR adds the option to use any element or component for the label of the items in a radio- or checkbox-group.
Previously it was only possible to generate Strings from the underlying objects by using the `label` property:
```kotlin
val label = ComponentProperty<(item: T) -> String> { it.toString() }
```
Both components now feature a dedicated `labelRendering` property that can be used to override the default rendering process and specify custom layouts.  
The `labelRendering` property is a lambda that takes each underlying `item: T` and renders the respective label.  
By default the label is rendered based on the `label` property.
```kotlin
// RadioGroupComponent:
val labelRendering = ComponentProperty<Div.(item: T) -> Unit> { /* rendering based on 'label' by default */ }
// …
```

Use any element/component as a label in radio- and checkbox-groups

---

components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

I tried to override the Slider Themes in a custom Theme using:
private val _slider = super.slider
override val slider: SliderStyles = object : SliderStyles by _slider {
override val horizontal: SliderCoreStyles = object : SliderCoreStyles by _slider.horizontal {
...
}
}
But it did not work. I realized, that the problem is with the SliderStyles.core(...) in:
https://github.com/jwstegemann/fritz2/blob/71d13d7888de1914c537c4c93ec071c81ea90fb1/styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt#L734
The Problem is that when using delegations, we actually have two SliderStyles instances, the base instance, and the custom instance which uses delegations to extend the base instance. 
The SliderStyles.core(...) runs in the base implementation instead of the custom implementation and …

fixed slider styling with delegations

---

components/src/jsMain/kotlin/dev/fritz2/components/components.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

This PR improves the following aspects of a modal:
- scrolling behaviour: Per default there are some settings to enable scrolling automatically without any client side effort.
- width settings (API change): new name ``width`` instead of ``size`` to make the intention of the property more expressive. The predefined values remains the same, but it is also possible now to provide a custom width value like ``30rem`` or alike. The old API calls will be applied and result in the same visual apperance for now.
- vertical placement (API change): This replaces the old ``variant`` property, which won't lead into an error, but the functionality is disabled. Instead use the ``placement`` property to align a modal vartically: ``top`` (default), ``center``, ``bottom`` and ``stretch`` are the possible …

Rework modal

---

styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt

Use explicit type specification for `Icons`  in `DefaultTheme`

---

components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

`ToastComponent`s close-button is now rendered above the underlying content and uses correct margins.
Closes #465 .

Fix close-button margin in `ToastComponent`

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

This PR renames the `discreet` alert-variant to `ghost` in order to match the common naming scheme of fritz2.
All references of `discreet` have to be changed:
```kotlin
alert {
variant { discreet } // <-- previously
variant { ghost } // <-- now
}
```
Closes #439 .

Rename alert variant `discreet` to `ghost`

---

components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

This PR adds two convenience functions `alertToast` and `showAlertToast` which can be used to easily create toasts with alert's as their content.
New functions:
```kotlin
fun showAlertToast(
styling: BasicParams.() -> Unit = {},
baseClass: StyleClass = StyleClass.None,
id: String? = null,
prefix: String = "toast-alert",
build: AlertComponent.() -> Unit
)
fun alertToast(
styling: BasicParams.() -> Unit = {},
baseClass: StyleClass = StyleClass.None,
id: String? = null,
prefix: String = "toast-alert",
build: AlertComponent.() -> Unit
): SimpleHandler<Unit>
```
Example usage:
```kotlin
showAlertToast(buildToast = {
}) { 
// toast-properties:
duration(6000)
// setup of the alert
alert {
title("Alert-Toast")
content("Alert in a toast")
severity { /* some severity */ }
variant { leftAccent }
}
} …
```

Add convenience functions to create toasts with alert-content

---

components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
components/src/jsMain/kotlin/dev/fritz2/components/box.kt
components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt

This PR deprecates the `box` factory method in favor of `div` because, in combination with fritz2.styling, it offers the exact same functionality. All calls of `box` will have to be replaced eventually.
Closes #379 .

Deprecate `box` in favor of `div`

---

components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

This PR cleans up the `ToastComponent` code. This includes:
- Adding styling-options to the theme
- Use correct z-indizes
- General code-cleanup
---
- `Theme().toast.base` has been renamed to `Theme().toast.body` and might break themes that have custom toast-styles
---
Closes #388 .
Closes #396 .

Rework `ToastComponent`

---

components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
components/src/jsMain/kotlin/dev/fritz2/components/modal/component.kt

Until now the `close` handler was injected directly into the main configuration scope of a modal. With repsect to [EfC 416]((#item-416-never-provide-parameters-within-components-main-context)) this is now changed. The handler only gets injected into the `content` property, where it is considered to be used.
Just move the handler parameter from the `build` expression of modal into the `content` property:
```kotlin
// old
clickButton {
text("Custom Close Button")
} handledBy modal { close -> // injected at top level
content { 
clickButton {icon { logOut } } handledBy close
}
}
// new
clickButton {
text("Custom Close Button")
} handledBy modal {
content { close -> // injected only within content
clickButton {icon { logOut } } handledBy close
}
}
```
fixes #482

Move Modal's close handler into content property

---

components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentGroup.kt
components/src/jsMain/kotlin/dev/fritz2/components/radios/componentGroup.kt

This PR removes the deprecated `direction `-api from `RadioGroupComponent` and `CheckboxGroupComponent`.
Use `orientation instead`.
---
Closes #418 .

Remove deprecated `direction`-api from `RadioGroupComponent` and `CheckboxGroupComponent`

---

components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
components/src/jsMain/kotlin/dev/fritz2/components/datatable/foundation.kt
components/src/jsMain/kotlin/dev/fritz2/components/datatable/selection.kt
components/src/jsMain/kotlin/dev/fritz2/components/validation/validation.kt
core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsTest/kotlin/dev/fritz2/binding/substores.kt

Removes the `RootStore` dependency in the `SubStore`, so that `SubStore`s can be created by calling `sub()` function implemented in `Store` interface. Therefore it is now possible to create a `SubStore` from every `Store` object.
Because one `SubStore` generic type gets obsolete, it will break existing code, but it is easy to fix that. Just remove the first not type parameter.
```kotlin
// before
class SubStore<R, P, T> {}
// now
class SubStore<P, T> {}
```
```kotlin
// before
val addressSub: SubStore<Person, Person, Address> = store.sub(addressLens)
// now
val addressSub: SubStore<Person, Address> = store.sub(addressLens)
```

Allow `sub()` on all `Store´s

---

components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/foundations/mixins.kt
components/src/jsMain/kotlin/dev/fritz2/components/inputField/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/typeAhead.kt
components/src/jsMain/kotlin/dev/fritz2/components/typeAhead/component.kt
core/src/jsMain/kotlin/dev/fritz2/binding/store.kt

Adds a TypeAhead component to fritz2's component portfolio.
A TypeAhead offers the possibility to input some string and get some list of proposals to choose from. This is reasonable for large static lists, that can't be managed by SelectFields or RadioGroups or where the proposals rely on a remote resource.
Example usage:
```kotlin
val proposals = listOf("Kotlin", "Scala", "Java", "OCaml", "Haskell").asProposals()
val choice = storeOf("")
typeAhead(value = choice, items = proposals) { }
```
For further details have a look at our [KitchenSink](https://components.fritz2.dev/#TypeAhead)
fixes #373

Add TypeAhead Component

---

core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt

because Chrome and Safari sometimes offer instances of `Event` and not(!) `InputEvent` to a listener on "input", we have to change the type of an `InputEvent` to just `Event`.
For example this is the case when selecting an entry from a datalist.

fix type of InputEvent

---

components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
components/src/jsMain/kotlin/dev/fritz2/components/appFrame/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/appFrame/scope.kt
components/src/jsMain/kotlin/dev/fritz2/components/appFrame/service.kt
components/src/jsMain/kotlin/dev/fritz2/components/box.kt
components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentSingle.kt
components/src/jsMain/kotlin/dev/fritz2/components/menu.kt
components/src/jsMain/kotlin/dev/fritz2/components/menu/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/menu/context.kt
components/src/jsMain/kotlin/dev/fritz2/components/menu/entries.kt
components/src/jsMain/kotlin/dev/fritz2/components/radios/componentSingle.kt
components/src/jsMain/kotlin/dev/fritz2/components/switch/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/toast/component.kt
core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

The `appFrame` component uses now different `ColorScheme`s to coloring itself.
The `menu` component can now contain `submenu`s:
```kotlin
menu {
header("Entries")
entry {
text("Basic entry")
}
divider()
custom {
pushButton {
text("I'm a custom entry")
}
}
submenu {
icon { menu }
text("Sub Menu")
entry {
icon { sun }
text("Entry with icon")
}
entry {
icon { ban }
text("Disabled entry")
disabled(true)
}
}
}
```

Use colors in `appFrame` and added `submenu` in `menu` component

---

components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/datatable/foundation.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt

The DataTable now reacts much smoother to changes of its content, so that:
- a row itself (the `tr` tag) is not deleted until the `id` of its row disappears
- a cell (the `td` tag) is only rendered if its `String` represenatation via its `Lens` changes or some of the state related properties like the selection state or the sorting
This improves the handling of editable cells, as one can now *tab* through a row without rerendering it and therefore keeping the focus stable so it advances by default to the next column.
Be aware that you must adapt to those changes, if your editable DataTable relies on changes to one arbitrary (maybe not rendered property!) field of a model. This will not work any longer and must be solved otherwise.
fixes #404
fixes #509

Optimize DataTable's reactive rendering

---

components/src/jsMain/kotlin/dev/fritz2/components/popup.kt
components/src/jsMain/kotlin/dev/fritz2/components/popup/component.kt
components/src/jsMain/kotlin/dev/fritz2/components/tooltip.kt
components/src/jsMain/kotlin/dev/fritz2/components/tooltip/component.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt

This PR deals with the new `TooltipComponent`
A `tooltip` should be used to display fast information for the user.
The individual `text` will be shown on hover the `RenderContext` in which be called.
This class offers the following _configuration_ features:
- `text` can be a `vararg`, a flow, a list, a flow of list of String or a simple string, optional can be use the @property `textFromParam`.
- `placement` of the `text` around the `RenderContext`in which be called. Available placements are `top`, `topStart`, `topEnd`, `bottom`, `bottomStart`, `bottomEnd`, `left`, `leftStart`, `leftEnd`, `right`, `rightStart`, `rightEnd`.
Example usage:
```kotlin
span {
+"hover me"
tooltip("my Tooltip on right side") {
placement { right }
}
}
span {
+"hover me to see a multiline tooltip"
tooltip("first …
```

Add `TooltipComponent`

---

core/src/jsMain/kotlin/dev/fritz2/dom/window.kt

Apply fix from version 0.12 also to `Window` object.

Handle possible ClassCastException

---

core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsTest/kotlin/dev/fritz2/dom/attributes.kt

Null values will now prohibit the setting of an attribute with String `null` as value; instead no attribute will be set at all.

Improve null value handling for attribute setting

---

core/src/jsMain/kotlin/dev/fritz2/webcomponents/webcomponents.kt
core/src/jsTest/kotlin/dev/fritz2/webcomponents/webcomponent.kt

I was running into a similar issue to what is described in Issue #83, and while investigating the codebase to see what might be causing it, I saw that you were planning to move to using a `SharedFlow` for Web Component attribtues anyway. I believe that this will solve the issue, because `SharedFlow` is a hot flow, so we wouldn't need to wait for someone to consume the flow in order to give `attributeChangedCallback` a value. Hope this helps!

Use a SharedFlow for Web Component attribute changes

---

components/src/jsMain/kotlin/dev/fritz2/components/appFrame/component.kt

As discussed with Jens. Fixes issue #550 where on Mobile (Safari), UIs with AppFrame skip to the top of the page after leaving any field. Fix needed in January 2022 for a UI in production.
https://github.com/jwstegemann/fritz2/issues/550

Fix for issue #550: Removed touchends-event scrolling from appFrame component

---

components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt
core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
core/src/jsTest/kotlin/dev/fritz2/dom/html/events.kt
core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt

This PR improves the whole key event handling API by the following aspects:
* improved `Key`-class based upon a new concept of `Modifier`-interface, which enables constructing nice key shortcut combinations like "Strg + K" or "Shift + Alt + F" or alike.
* add some convenience methods to improve the event handling for `KeyboardEvent`s: `keys()`
* improved `Keys`-object with predefined common keys like `Tab`, `Enter` but also the modifier keys like `Alt`, `Shift`, `Meta` and `Control`
* mark some special interest functions as _deprecated_ in favour of using the new `keys` functions, which does the heavy work without being too specialized.
The new key API allows easily defining combinations of keys with modifier keys, constructing those from a `KeyboardEvent` and prevents meaningless …

Improve Key API and keys event handling

---

core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
core/src/jsTest/kotlin/dev/fritz2/dom/tag.kt

It seems to be more flexible to access the annex (neighborhood) - context of a Tag by a property instead of a render-like method.
```kotlin
div(id = contentId) {
div {
+"inner div"
}.annex.apply {
span { +"outer div" }
}
span { +"after inner div" }
}
```
results in 
```html
<div>inner div</div><span>outer div</span><span>after inner div</span>
```

Access annex via property

---

core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt
core/src/jsTest/kotlin/dev/fritz2/binding/handlers.kt
core/src/jsTest/kotlin/dev/fritz2/binding/mount.kt
core/src/jsTest/kotlin/dev/fritz2/binding/store.kt
core/src/jsTest/kotlin/dev/fritz2/remote/websocket.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
core/src/jsTest/kotlin/dev/fritz2/repositories/rest/rest.kt

To make sure, that the coroutine of a `Store` or `RenderContext` is not cancelled by an uncaught exception, we changed the way of exception handling in fritz2:
You cannot provide a lambda specifying, how to handle uncaught exceptions, to a handler anymore. Just use `try ... catch` 
- in your handler's code, 
- in any intermediate operation on the `Flow` or  
- by using `.catch()` on the `Flow` 
to deal with an exception the way you want.
An exception you did not catch earlier (by `try ... catch` or `.catch()` on a `Flow`) will be caught by fritz2 for any type of handler, including ad hoc handlers.
By default, the exception will be just logged to the console. You can change this behavior be overriding the `errorHandler` function of your `Store`, `RenderContext`, etc.

Fixed exception handling in Handlers

---

core/src/jsMain/kotlin/dev/fritz2/remote/auth.kt
core/src/jsMain/kotlin/dev/fritz2/remote/http.kt
core/src/jsTest/kotlin/dev/fritz2/remote/auth.kt
gradle.properties
test-server/src/main/kotlin/dev/fritz2/Server.kt

`Authentication.getPrincipal()` function returns the principal also when pre-setting it before any process is started

---

.github/workflows/build.yml

Cancels not needed build jobs (see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow)

Cancel not needed build job runs

---

core/src/jsMain/kotlin/dev/fritz2/core/handlers.kt
core/src/jsMain/kotlin/dev/fritz2/core/job.kt
core/src/jsTest/kotlin/dev/fritz2/core/handlers.kt
core/src/jsTest/kotlin/dev/fritz2/test.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
headless/src/jsTest/kotlin/dev/fritz2/headless/test.kt

- add new `OnlyOnceFlow` flow with corresponding `flowOnceOf` factory
- use this new flow inside the `invoke` methods of a handler, so that it is guaranteed the value is really emitted only once
- enable `toggle` handler of `OpenClose` again including its unit tests
- add unit tests for new handler

Fix invocation of Handlers

---

core/src/jsMain/kotlin/dev/fritz2/core/attributes.kt
core/src/jsTest/kotlin/dev/fritz2/core/attributes.kt

Some attributes need a special treatment in order to react to changes as the DOM API is a bit cumbersome there (for example `HTMLInputElement.value` or `HTMLInputElement.checked`. This PR reintroduces the former solution for handling those corner cases and adds dedicated unit tests for those.
PR #582 as part of the same milestone introduced new API with the bug, so this fix does not need to be announced within the release note!

Reintroduce edge case treatment of some special tag attributes

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/checkboxGroup.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/dataCollection.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/disclosure.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/inputField.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/listbox.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/menu.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/modal.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/popOver.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/radioGroup.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/switch.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/tabGroup.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/textArea.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
www/src/pages/headless/inputField.md
www/src/pages/headless/textArea.md

- Adds lot of explicit IDs for the headless components, so the automatic testing will become much easier: The detection of an HTML element of the component can now be based upon deterministic IDs.
- Add third button for modal demo, so the tabbing direction will become obvious
- Add missing keyboard and mouse interaction sections for `inputField` and `textArea` component's documentation.

Improve Headless Components and some Documentation

---

core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/attributes.kt

Streamline internal behavior of the `attr()` functions by using it each other. This also fixes the issues that it is not possible to remove an attribute by using `null` as value.

Fix functionality of `attr()` functions

---

.github/workflows/release.yml

Fix call of other workflow www.yml in release.yml. See https://github.community/t/reusable-yml-in-local-repository-cannot-be-found-if-executed-in-steps/230319

Fix release.yml workflow

---

README.md

Workaround for strange behavior of GitHub pages (bug?). The .png file can't be resolved by its correct path. Therefore, I use an alternative link to the file instead...

Fix broken link to fritz2_cycle_of_life.png

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/inputField.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/textArea.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
www/src/pages/headless/inputField.md
www/src/pages/headless/modal.md
www/src/pages/headless/textArea.md

- removes ``disabled`` and ``placeholder`` properties; both aspects needs to be handled from the outside anyway (in order to react to state changes for example). There is no benefit to expose those two from the headless level.
- correct small typing aspect within modal documentation
fixes #619

Improve textfield API

---

headless-demo/README.playwright.md
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/inputField.kt
headless-demo/tests/checkbox.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
www/src/pages/headless/inputField.md

The ``type`` is no longer a (poorly) encapsulated attribute offered by ``inputField``. This makes the internal code much simpler and would theoretically allow to choose the tag for ``inputTextfiled`` in the future.
fixes #678
- correct small ID setting mistake in checkboxGroup component
- add some useful remark in the playwright readme for local testing.

Improve Headless Input API

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/aria.kt

Former to this PR components based upon PopoverPanel set the ``aria-haspopup`` property always to true.
According to its [definition](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup#description) the value only might be ``true`` if the component represents some "menu". In other cases there are dedicated values, that should be set:
- menu
- listbox
- tree
- grid
- dialog
This PR adds a parameter for this value to the ``PopUpPanel``, so that every component has to pass a value.
The following headless components now sets the following values accordingly:
- ``listbox`` -> ``listbox``
- ``menu`` -> ``menu``
- ``popOver`` -> ``dialog``
- ``tooltip`` -> ``dialog``
The attribute is set defensively, so that a user can always overrule those defaults by …

Repair aria-haspopup for PopUpPanel based components

---

headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
www/src/pages/headless/headlessComponents.md

I order to render the floating content of a PopUpPanel based component, we have defined a static z-Index with value ``30`` for the popper div, which can't be styled in a safe and reliable way from the outside.
This value corresponds to the median value of the predefined [tailwindcss](https://tailwindcss.com/docs/z-index) z-indices. 
fixes #670

Add default z-Index for PopUpPanel

---

examples-demo/build.gradle.kts
headless-demo/build.gradle.kts
headless-demo/src/commonMain/kotlin/dev/fritz2/headlessdemo/dataCollectionModel.kt

Lenses generation was not possible due to oversimplification of the ksp config section in the build.gradle.kt. In order to preserve regressions on this topic, the ``@Lenses`` annotation were enabled again for our models in the demo, even though the generated lenses are currently not used.
Not worth mentioning in the release note!

Repair the ksp config

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/DatabindingProperty.kt

As for some components it is absolutely mandatory to have some data-binding, in order to avoid some NPE at runtime, we have added default appropriate data-bindings for those. Additionally, some warning messages will be logged into the console in such a fallback case, so the user gets a hint, what he has forgotten to set. 
fixes #667

Add default data-binding as fallback for headless components

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/tabGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/focus.kt
www/src/pages/headless/tabGroup.md

This PR fixes two main issues and introduces some new functionality as side effect, that might be useable for dealing with similar focus management situations.
The focus-trap is now also reactive by adding a new variant function ``trapFocusWhenever`` to the established ``trapFocus`` one. Theis alternative requires  some boolean flow as first parameter that acts as a conditional decider: Only on ``true`` values on the flow the focus-trap will get established; on ``false`` values it will get disabled.
This is very useful for situations, where some kind of "open" state (as for ``PopUpPanel`` based components for example) triggers the visibility of a content, where the trap should be active. After closing however, the tab should be freed again, so that the user can continue to tab through the …

Improve Focus Management on various headless Components

---

headless-demo/tests/datacollection.datatable.spec.ts
headless-demo/tests/datacollection.gridlist.spec.ts

Due to the change of filtering behaviour of PR #692, the amount of selected items changes now. The test expectations now corresponds to the actual remaining selected persons.
Does not need to be mentioned in the release note.

Fix test expectations

---

core/src/jsMain/kotlin/dev/fritz2/remote/auth.kt

The default status code for a failed authentication is reduced to only 401.
Before also the 403 was part of the status codes and would trigger the handleResponse interception method and starts a new authentication recursively. This is of course a bad idea, as the *authorization* will not change by the *authentication* process. Therefore the default http status for launching an authentication process should be only 401.
If you have some service that really relies on the 403 for the authentication, please adopt to the http semantics and change that to 401 instead.
fixes #700

Repair remote auth middleware - prevent endless loop for 403 response

---

build.gradle.kts
lenses-annotation-processor/build.gradle.kts

Upgrade to Kotlin version 1.7.20 and compatible plugins & libs for the 0.14 legacy release.

Upgrades to Kotlin 1.7.20 (For 0.14 legacy branch)

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/tooltip.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/DatabindingProperty.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/Property.kt

As explained in #698, default data bindings weren't set in some cases. This PR fixes this issue by adding an `emptyFlow()`  as fallback for the `DatabindingProperty`s `data` property. This prevents the NPE at runtime and makes it still possible to check for an unset data binding inside the headless component itself via the `isSet` property.
All components affected by this issue now check for the unset data binding and write a warning in the browser console in case it was not set. The warning now also contains the components actual DOM node for convenience, since Firefox and Chrome make it possible to jump to the element inside the UI by clicking on the object in the warning. This should make it easier to spot the component with the unset data binding.
The PR also fixes an issue with the …

Fix default data bindings

---

core/src/commonMain/kotlin/dev/fritz2/core/lens.kt
core/src/commonTest/kotlin/dev/fritz2/core/lens.kt
core/src/jsMain/kotlin/dev/fritz2/core/store.kt
core/src/jsMain/kotlin/dev/fritz2/core/substores.kt
core/src/jsTest/kotlin/dev/fritz2/core/nullable.kt.kt
core/src/jsTest/kotlin/dev/fritz2/core/substores.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/dataCollection.kt
www/src/pages/docs/30_State Management.md

If you have a `Store` with a nullable content, you can use `orDefault` to derive a non-nullable `Store` from it, that transparently translates a `null`-value from its parent `Store` to the given default-value and vice versa.
In the following case, when you enter some text in the input and remove it again, you will have a value of `null` in your `nameStore`:
```kotlin
val nameStore = storeOf<String?>(null)
render {
input {
nameStore.orDefault("").also { formStore ->
value(formStore.data)
changes.values() handledBy formStore.update
}
}
}
```
In real world, you will often come across nullable attributes of complex entities. Then you can often call `orDefault` directly on the `SubStore` you create to use with your form elements: 
```kotlin
@Lenses
data class Person(val name: String?)
//... …
```

Improve handling of nullable values in Stores

---

core/build.gradle.kts
core/src/jsMain/kotlin/dev/fritz2/history/history.kt
core/src/jsTest/kotlin/dev/fritz2/history/history.kt
headless/build.gradle.kts
www/src/pages/docs/30_State Management.md

Simplifying the history feature, which includes the following changes:
* history is synced with `Store` by default
```kotlin
// before
val store = object : RootStore<String>("") {
val hist = history<String>().sync(this)
}
// now
val store = object : RootStore<String>("") {
val hist = history() // synced = true
}
```
* renamed `reset()` method to `clear()`
* renamed `add(entry)` method to `push(entry)`
* removed `last()` method, cause with `current: List<T>` every entry is receivable
* changed default `capacity` to `0` (no restriction) instead of `10` entries
fixes #665

Simplify `history` feature

---

core/src/jsMain/kotlin/dev/fritz2/core/store.kt
core/src/jsMain/kotlin/dev/fritz2/core/substores.kt
core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt
core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/dataCollection.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
www/src/pages/docs/30_State Management.md
www/src/pages/docs/50_Routing.md
www/src/pages/recipes/Recipes.md.bak

Exposing only the public `Store<T>` type in fritz2's API, instead of the internal types `RootStore` or `SubStore` for simplifying the use of derived stores.
```kotlin
// before
val person: RootStore<Person> = storeOf(Person(...))
val name: SubStore<Person, String> = person.sub(Person.name())
// now
val person: Store<Person> = storeOf(Person(...))
val name: Store<String> = person.sub(Person.name())
```

Exposing `Store` interface  instead of internal `RootStore` and `SubStore`

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/toast.kt
headless-demo/tests/toast.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/toast.kt
www/src/pages/headless/toast.md

This PR adds a headless toast-component.
A toast is a component that can be displayed in specific areas of the screen for both a fixed or indefinite amount of time, similar to notifications.

Add headless `Toast` component

---

core/src/jsMain/kotlin/dev/fritz2/core/events.kt
core/src/jsMain/kotlin/dev/fritz2/core/listener.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/events.kt

It is now possible to listen on events in capture-phase (suffixed by `Captured`):
```kotlin
render {
div {
clicksCaptured handledBy store.save
}
}
```
For this we added new options to the `subscribe()` function which gives you a `Listener` for your event:
```kotlin
subscribe<Event>(name: String, capture: Boolean, init: Event.() -> Unit)
```
Using the `init`-lambda you can make settings to the captured event that have to be applied immediately.
We also fixed a bug when using `stopPropagation()` on a `Listener` which sometime did not work as expected.
fixes #552

Enable `Event` capturing

---

www/src/pages/docs/20_Render HTML.md

- className was used to apply CSS to a tag which does not work, it needs to be inlineStyle, 
- Fixed some text.

Fix CSS-Example and text

---

core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/tags.kt

Adds data-mount-point attribute to renderText generated mount-point tag.
fixes #729

Add missing data-attribute for mountpoints in renderText

---

core/src/jsMain/kotlin/dev/fritz2/tracking/tracking.kt
core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
examples/masterdetail/src/jsMain/kotlin/dev/fritz2/examples/masterdetail/masterdetail.kt

Until now, a tracker could distinguish several different transactions that could be passed as a parameter to the `track` function. This rarely needed functionality can be implemented by using multiple trackers (whose `data` streams can be combined if needed). This can significantly simplify the tracker's implementation. 
Specifying a transaction as a parameter of `track` is no longer possible. Appropriately, no `defaultTransaction` can be defined in the factory either. Likewise, the possibility to get a flow, which checks whether a certain transaction is running, by invoking the `Tracker` is omitted. 
Solves #736

Simplify Tracker to use Boolean as state

---

core/src/jsMain/kotlin/dev/fritz2/core/patch.kt
core/src/jsTest/kotlin/dev/fritz2/core/rendercontext.kt

The RC3 Release improved the rendering by dropping unnecessary mount-operations by PR #735.
Because of the changes, a regression appeared, which was caused by the shape of the `Patch`-implementations for the `renderEach`-functions: They were *data* classes and therefor it is quite easy to create equal patches, which then would be dropped by the mount-optimization! Imagine deleting the first item of a list at least twice for example.
This PR fixes the regression, so that a patch is always not equal to any other one (dropping data classes in favour of regular classes with object identity for equals).
In order to prevent a future regression some dedicated unit tests were added too.

Fix renderEach behaviour after regression by RC3 release

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt

There was a small remnant from the headless development within the popover component factory, that uses the `relative` class from tailwindcss - this is obviously wrong, as fritz2 is totally agnostic of CSS frameworks. So it is replaced now by some custom fritz2 prefixed class, that simply sets the `position=relative` too.
fixes #746

Substitute tailwindcss class with vanilla CSS

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt

If some user action emits navigation events for up, down, home or end keys to an empty data-collection, an `IndexError` was thrown. This is now fixed.

Fixes List Index related Bug in Headless DataCollection

---

core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt
core/src/jsTest/kotlin/dev/fritz2/routing/routing.kt

This PR fixes an issue in `Router` class where on page load the default route is used when no `window.location.hash` is set in the URL. This is not correct in cases where later on the `window.location.hash` gets cleared via JS. In this cases the router does not navigate automatically to the default route, which is not consistent.

Fix navigation issue in `Router`

---

core/src/commonMain/kotlin/dev/fritz2/validation/validation.kt
core/src/commonTest/kotlin/dev/fritz2/validation/test/validation.kt
core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
core/src/jsTest/kotlin/dev/fritz2/validation/validation.kt

Real world domain objects are in most cases forms a deep object hierarchy by composing dedicated types in a sensefull way, for example some `Person` consists of fields like `name` or `birthday` but also complex fields like some `Address`, which itself represents some domain aspect with basic fields.
As validation is most of the time tied to its corresponding domain type, the validators mirror the same hierarchy as the domain classes. Thus they must be composable in the same way, the domain types are composed.
This was prior to this PR not supported by the 1.0-RC releases!
The API of the `Validation` type changes just a little: The `validate` lambda expression now provides no longer a (domain) type `D`, but an `Inspector<D>`! There are now two `invoke` functions that take as first …

inspector based validation

---

core/src/commonMain/kotlin/dev/fritz2/validation/validation.kt
core/src/commonTest/kotlin/dev/fritz2/validation/test/validation.kt
core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
examples/validation/src/jsMain/kotlin/dev/fritz2/examples/validation/validation.kt

This PR changes the `Validation`'s metadata type to not be explicitly be nullable. Nullable types are still allowed, however.
The `ValidatingStore` API has been changed accordingly.
> **Important:** PR #761 needs to be merged before this one
```kotlin
@JvmInline
value class Validation<D, T, M>(private inline val validate: (Inspector<D>, T?) -> List<M>) {
operator fun invoke(inspector: Inspector<D>, metadata: T? = null): List<M> = this.validate(inspector, metadata)
operator fun invoke(data: D, metadata: T? = null): List<M> = this.validate(inspectorOf(data), metadata)
}
```
```kotlin
@JvmInline
value class Validation<D, T, M>(private inline val validate: (Inspector<D>, T) -> List<M>) {
//                                                                         ^^^
// …
```

Validation: Remove explicit nullability from metdata type

---

lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LensesProcessor.kt
lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lens/LensesProcessorTests.kt
www/src/pages/docs/50_StoreMapping.md

In order to make the combination of automatically generated lenses by the `@Lenses`-annotation more user friendly, this PR introduces a new feature: The annotation processor now creates also extension functions to enable the fluently chaining of lenses like this:
With this PR you can use:
`Model.foo().bar()`
instead of
`Model.foo() + Foo.bar()`
For more examples and explanation have a look at the [corresponding section](https://www.fritz2.dev/docs/storemapping/#combining-lenses) of the fritz2 documentation.
fixes #497

Generate extension functions for Lens-Chaining to enable some fluent-style-API

---

core/src/commonMain/kotlin/dev/fritz2/validation/validation.kt
core/src/commonTest/kotlin/dev/fritz2/validation/test/validation.kt

For convenience reasons it is now possible to call a validator with metadata type `Unit`without the metadata parameter.
Imagine a `Validator`of type `Validator<SomeDomain, Unit, SomeMessage>`:
```kotlin
data class SomeDomain(...) {
companion object {
val validator: Validator<SomeDomain, Unit, SomeMessage> = validation { inspector -> ... }
//                                   ^^^^
//                                   no "real" metadata needed
}
}
val myData: SomeDomain = ...
// now invoke the execution process...
// old
SomeDomain.validator(myData, Unit) // need to pass `Unit`!
// new
SomeDomain.validator(myData) // can omit `Unit`
```

Adds convenience execution functions for Unit metadata in validators

---

core/src/commonMain/kotlin/dev/fritz2/core/inspector.kt
core/src/commonMain/kotlin/dev/fritz2/core/lens.kt
core/src/commonTest/kotlin/dev/fritz2/core/inspector.kt
core/src/jsMain/kotlin/dev/fritz2/core/substores.kt
core/src/jsTest/kotlin/dev/fritz2/core/inspector.kt
core/src/jsTest/kotlin/dev/fritz2/core/store.kt

This PR adds an `Inspector.mapNull()` extension function that works like `Store.mapNull()`.
Just like on a Store, a default value is passed to the method that is used by the resulting store when the parent's value is `null`.
Additionally, the behavior of `Store.mapNull()` has been changed so that the path of the derived Store is the same as in the parent Store. This is the correct behavior as a Store created via `mapNull()` does not technically map to another hierarchical level of the data model. As a result, `mapNull()` works the same on both Stores and Inspectors, making the validation process more straight-forward. Previously, the Store's id has been appended to the path upon derivation.
This PR might potentially be API breaking as the behavior of `Store.mapNull()` regarding the …

Add `Inspector.mapNull()` method and fix `Store.mapNull()` path

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt

This PR fixes a problem where a PopUpPanel's arrow would initially be visible regardless of the popup being hidden.
Closes #774

Fix `PopUpPanel` arrow initially showing regardless of the popup's open state

---

www/src/pages/docs/50_StoreMapping.md

The Arrow website has been updated, and now the documentation about lenses lives somewhere else

Fix link to Arrow docs

---

.github/workflows/build.yml
build.gradle.kts
core/api/core.api
headless/api/headless.api

Closes #199 
We also found that many people forget to run `apiDump` before committing, so it's useful to auto-commit it if any change is detected. This makes it easier to figure out the real API changes.

Add binary compatibility validation

---

core/src/jsTest/kotlin/dev/fritz2/core/rendercontext.kt
www/src/pages/docs/30_Render HTML.md

This PR and PR #783 added new utility `render`-functions inside `RenderContext`.
The `renderIf(predicate: (V) -> Boolean)` function only renders the given `content`, when the given `predicate` returns `true` for the value inside the `Flow<V>`.
```kotlin
val store = storeOf<String>("foo")
render {
store.data.renderIf(String::isNotBlank) {
p { +it }
}
}
```
The `renderNotNull()` function only renders the given `content`, when the value inside the `Flow<V?>` is not null.
```kotlin
val store = storeOf<String?>(null)
render {
store.data.renderNotNull {
p { +it }
}
}
```
The `renderIs(klass: KClass<W>)` function only renders the given `content`, when the value inside the `Flow<V>` is a type of `klass`.
```kotlin
interface I
class A: I
class B: I
val store = storeOf<I>(A())
render { …
```

New utility `render`-functions for `RenderContext`

---

headless-demo/playwright.config.ts
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/popOver.kt
headless-demo/tests/components/modal.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt

PopUpPanel is not focusable by default. In Chrome setFocus does nothing here, but in Firefox the current focus gets lost, when setFocus is called on a not-focusable element.

Semove setFocus from PopUpPanel

---

core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt
core/src/jsTest/kotlin/dev/fritz2/core/mount.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/portalling.kt

The lifecycle function `beforeUnmount` did not work properly in some reactively nested scenarios.
In a simple example with one `Store` and a corresponding `Store<*>.render` it is working without problems, but when nesting render-blocks, it is only called for the outer `MountPoint`.
Example:
```kotlin
val outerStore = storeOf(Id.next())
val innerStore = storeOf(Id.next())
input {
type("Button")
value("Update Outer Store")
}.clicks.map { Id.next() } handledBy outerStore.update
input {
type("Button")
value("Update Inner Store")
}.clicks.map { Id.next() } handledBy innerStore.update
outerStore.data.render {
p { +it }
afterMount { _, _ -> console.log("outer afterMount") }
beforeUnmount { _, _ -> console.log("outer beforeUnmount") }
innerStore.data.render {
p { +it }
afterMount { _, _ -> …
```

#782 Fix reactively nested beforeUnmount Calls

---

core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
core/src/jsTest/kotlin/dev/fritz2/core/mount.kt

In more complex rendering hierarchies child-nodes might be unmounted, before the parents get unmounted. Thereforce we have to check, whether the used job is active, otherwhise we will get an exception.

fix afterUnmount crashes due to job cancellation

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/listbox.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/menu.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/popOver.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/toast.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/tooltip.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/toast.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/portalling.kt

The default `z-index`-Stylings are removed entirely from the portal-factory. As the portal-containers can be defined by the user, there is no more need to "hide" them with `display-contents` and implement some `z-index` behavior for their children.
This is a huge step to consequently remain headless and be agnostic of any styling!
fixes #799
fixes #802

Removes portal stylings

---

headless/api/headless.api
headless/src/commonMain/kotlin/dev/fritz2/headless/validation/validation.kt

The `ComponentValidationMessage` implements the `Message` interface, which is the building block for all validation related aspects in fritz2 and is also the default type for all `headless` components. It is definitely a `value` type from the domain perspective and thuis should be a `data class`. This makes it so much easier to filter duplicates for example.
That is why we change the type from an `open class` to a `data class`.
fixes #801

make ComponentValidationMessage a data class

---

serialization/build.gradle.kts
serialization/src/jsMain/kotlin/dev/fritz2/remote/serialization.kt
settings.gradle.kts

This (small) module includes a few functions which come in handy when working with fritz2's `http` module alongside `kotlinx-serialization`.

Serialization module

---

www/src/pages/headless/headlessComponents.md
www/src/pages/headless/listbox.md
www/src/pages/headless/menu.md
www/src/pages/headless/modal.md
www/src/pages/headless/popOver.md
www/src/pages/headless/toast.md
www/src/pages/headless/tooltip.md

Updates some documentation sections due to the portalling mechanism:
- add some info-boxes to all headless components, relying on the portal-initialization
- update the general portal doc to remove the outdated `z-index` descriptions
fixes #809

Update the headless documentation of portalling

---

core/src/jsMain/kotlin/dev/fritz2/core/store.kt

In #806 we created a protected runWithJob-Function within the RootStore to allow using the WithJob-Scope within a RootStore without allowing all handledBy functions be statically imported. To avoid excessive usage of the WithJob-Scope, we made this function protected.
After using the new RC in different projects we noticed, that not having a public runWithJob forces the developers to create workarounds for legitimate reasons. Therefore it seems to be a better idea to make runWithJob public.

make RootStore.runWithJob public

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/listbox.kt
headless-demo/tests/components/datacollection.datatable.spec.ts
headless-demo/tests/components/listbox.spec.ts
headless-demo/tests/components/menu.spec.ts
headless-demo/webpack.config.d/tailwind.config.js
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
kotlin-js-store/yarn.lock
versions.properties

- removes obsolete and overseen `z-index` from `PopUpPanel` static style classes
- removes static `<div>`-tag as root element of any `PopUpPanel`. Instead, this `tag` is created by the provided `tagFactory`.This reduces the DOM complexity and enables clients to model their floating content closer to any template.
- adjust UI-tests due to new DOM structure within the demo components
- downgrade external `scroll-into-view-if-needed` lib version to fit to code base
fixes #820

Improves PopUpPanel Rendering

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt

The previous event handling lead to interrupted keydown events, so that automated tests were to fast. With this change the event handling got more stable for fast automated tests.

improve event handling in dataCollection

---

core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/test.kt
examples/validation/src/commonMain/kotlin/dev/fritz2/examples/validation/validator.kt
headless-demo/package-lock.json
headless-demo/package.json
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
versions.properties
www/src/pages/docs/30_Render HTML.md

needs #822 to be merged first!
- removes `addToClasses` functions. Migration: Just rename all occurrences to `className`.
- substitutes the internal class name management with a `MutableStateFlow` based approach, where the former manages all different portions of the overall class names, so those can get merged appropriately and mounted only once into the tag's `class` attribute.
- add a new `className`-function variant: This generic function accepts some `Flow[T]`, which is then be used by some lamba expression to generate the class names. Additionally the calles must also provide some initial `T`, which is used to create the
  initial class names that gets set immediately to the DOM, without needing to wait for the flow's first value.
- add unit tests for new `className`-function
- add …

Improves and enhances the reactive styling

---

core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
core/src/jsTest/kotlin/dev/fritz2/validation/validation.kt

Up to the `RC5 / RC6` version of fritz2, the `messages()`-function on `Store`s just matched the *exact* path. This behavior was changed by those release candidates: Right now all messages that matches the exact path, but also all messages machining the sub-path will be collected.
Our experience has shown, that this behavior change was a mistake, as the 80% use case is to collect all messages for an exact path. Most of the time one has dedicated form elements, that fit exactly one property of a model and thus should only show messages for itself. It is very rarely happening, that all messages of a sub-model should be shown all together.
This is why this PR changes again the default behavior, but also introduces a dedicated variant for collecting all sub-model messages with the new …

Improves the validation message filtering and resets the default behaviour

---

core/src/jsMain/kotlin/dev/fritz2/core/foundation.kt
core/src/jsMain/kotlin/dev/fritz2/core/scope.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/toast.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/portalling.kt

In #781 we added portalling, but portals currently do not inherit any scope.
In this PR portal-containers get a scope of some defined parent tags.
We have two types of portals:
Bound to the ViewPort:
- Modal
- Toast
These Portals will inherit the Scope of the PortalRoot, which inherits the Scope of its parent (usually the main render Function). 
Both the portalRoot() function and the global render() function got a scope parameter, so the user can set scopes as for every tag.
The second type of portals is bound to a reference element:
- listbox
- menu
- popOver
- tooltip
These portals inherit the scope of their reference element, to which they get aligned.

scope handling for portal containers

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/focus.kt

The current code contains lots of statements like
state.flatMapLatest { value ->
clicks.map { ... }
} handledBy ...
The problem here is, that
1. the listener is attached after a minimal delay
2. event-calls might get lost, because the outer flow changes
For flows, which represent a state, it should be no problem to use flatMapLatest, but because events are one-shot operations, they should not be used within another flow transformation. While it seems to work for normal usage, it causes lots of problems for automated ui-tests e.g. using playwright. Actions might get lost or are not ready yet, what causes failing/flaky tests.
With this PR i replaced all event-Flows within Flow-Transformations i could found. The replacement always a followed similiar pattern. The above example code would be …

avoid events in flatMapLatest

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
www/src/pages/headless/headlessComponents.md
www/src/pages/headless/listbox.md
www/src/pages/headless/menu.md
www/src/pages/headless/popOver.md
www/src/pages/headless/tooltip.md

- extends `arrow`-factory to take some `offset`-parameter alongside to the size parameter that is meant for changing width and height
- improves default styling, so that the arrow is located behind the panels content
- adds, corrects or improves API- and prose-documentation regarding the `PopUpPanel` usage, `arrow`-usage or `middleware`-usage.
This can be tested with the following snippet. Just paste it somewhere into the `headless-demo`:
```kotlin
popOver {
popOverButton(classes = "mr-3 mt-2") {
+"Click me"
}
popOverPanel("z-30 bg-gray-100") {
arrow("w-10 h-10", 25)
div("p-3 py-4") {
+"With Arrow Beneath Text!"
}
}
}
```

Improves PopUpPanel

---

core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/portalling.kt

In #829 we implemented a special scope inheritance for portal containers. 
Because of that the MountPoint (which is stored as Scope) was also overwritten. 
The MountPoint is also used for afterMounts/afterUnmounts, which are currently broken in portals. Therefore FocusTrap does also not always work in Modals.
With this PR the MountPoint in Portals got fixed, so that afterMounts/afterUnmounts continue to work as expected

fix mountpoint in portals

---

examples/tictactoe/src/jsMain/kotlin/dev/fritz2/examples/tictactoe/tictactoe.kt

In order to adapt better to bootstrap, reduce unnecessary `inlineStyle`-usage, the example gets streamlined a bit. Also, this might help to stop [confusing users](https://github.com/jwstegemann/fritz2/issues/831#issuecomment-1872299365).

Improves TicTacToe example

---

headless-demo/tests/components/listbox.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt

Due to PR #833 the closing mechanism of headless listbox has changed, so that clicking / pressing enter or space on the previously selected item did not close the listbox anymore. This commit restores the previous and desired behaviour again.
In order to avoid future regressions, a dedicated playwright test is added.

Fix Selection Behaviour of ListBox

---

examples/masterdetail/build.gradle.kts
examples/nestedmodel/build.gradle.kts
examples/tictactoe/build.gradle.kts
examples/todomvc/build.gradle.kts
examples/validation/build.gradle.kts
headless-demo/build.gradle.kts
www/src/pages/docs/10_Getting Started.md

Fixes implicit dependency errors in Gradle 8.5 by the ksp task.
line that causes the error
```
kotlin.sourceSets.commonMain { kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin") }
```
the error message:
```
FAILURE: Build failed with an exception.
* What went wrong:
Some problems were found with the configuration of task ':my-project:kspCommonMainKotlinMetadata' (type 'KspTaskMetadata').
- Gradle detected a problem with the following location: '/Users/jan/IdeaProjects/oe-auth-service/core/build/generated/ksp/metadata/commonMain/kotlin'.
Reason: Task ':my-project:jvmSourcesJar' uses this output of task ':my-project:kspCommonMainKotlinMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the …
```

Fix ksp configuration in projects

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt

This PR fixes a problem where a popover would close when selecting  a listbox item from a nested listbox.
When selecting an item from a nested listbox, the click event's `target` property differs depending on the OS the browser is running on. While the browser on MacOS sets the `target` to the actual element I clicked on, on Windows it sets the `target` to another element (in my case this was the portal root element).
This behavior seems to be browser-independent, but I only tested this for Edge and Safari on MacOS and Edge and Chrome on Windows.
This PR avoids this problem altogether by changing the event the listbox item listens to from `mousedown` to `click`. This way, the event listener registered by the `closeOnDismiss()` method does not run, because the event gets correctly …

Fix nested listbox selection behavior

---

headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/focus.kt

Using fritz2 Event-Flows the calls for preventDefault and stopImmediatePropagation will be delayed slightly, so that the Browser might already perform the Tab Operation. To prevent this behaviour we have to use a plain JS Listener, which directly calls preventDefault and stopImmediatePropagation.
It is difficult to reproduce this problem with user interaction, but Tabbing with Playwright-Tests on Firefox causes duplicate Tab events (Browser-Default + Fritz2-Focustrap). 
Using Event-Flows with preventDefault and/or stop(Immediate)Propagation might also cause other problems, but that there is no way to fix this globally in Fritz2, because Event-Handling heavily depends on Flows and Job-Handling.

fixing focustrap for firefox tests

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
www/src/pages/headless/radioGroup.md

RadioGroups are now focusable even is there is no option selected yet. If that is the case, only the first option becomes active and can be selected by pressing Space.
If there is one option selected, the component behaves the same way as before.
This fixes #770

Improves Focus Management of RadioGroups

---

lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LensesProcessor.kt
lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lens/LensesProcessorTests.kt

Obviously the ksp based LensesAnnotationProcessor was more resilient in the past before we upgraded to Kotlin 1.9.x and appropriate ksp with RC15.
We encountered some issues with generating lenses that only came with this bad warning:
```
w: [ksp] Unable to process:dev.fritz2.lens.LensesProcessor:   SomeClass
```
This was due to some not resolvable types inside the annotated data class, like calls to functions from other libs or delegated properties. With former ksp-versions those problems did not arise - so obviously ksp has evolved since then and got stronger constraints for the `evaluate`-function.
This PR fixes such issues, as we ignore everything from the annotated class but the primary constructor. The latter is the only interesting piece for our lens generation.

Make lenses genration more resilient with KSP >= 1.9.x

---

core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt
core/src/jsTest/kotlin/dev/fritz2/core/rendercontext.kt
www/src/pages/docs/30_Render HTML.md

With [fritz1.0-RC8](https://github.com/jwstegemann/fritz2/releases/tag/v1.0-RC8) we added a bunch of convenience-render-functions to reduce boilerplate-code within the ui-sections, such as `renderIf({/*some boolean expression */}) { ... }`. In many cases however, we have to work with boolean Flows which lead to code like this:
```kotlin
someBooleanFlow.renderIf({ it }) { 
/* render UI */ 
}
```
This looks not as clean as it could.
This PR adds two convenience functions `Flow<Boolean>.renderIfTrue(...)` and `Flow<Boolean>.renderIfFalse(...)` that render a given content if a boolean Flow's value is `true` or `false` respectively.
Examples:
```kotlin
val store = storeOf(true)
store.data.renderIfTrue {
// content is rendered if the Store's value is true.
// If the Store's value is false, …
```

Add `renderTrue` and `renderFalse` convenience functions

---

core/src/jsMain/kotlin/dev/fritz2/core/foundation.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsMain/kotlin/dev/fritz2/core/transitions.kt
examples/tictactoe/src/jsMain/kotlin/dev/fritz2/examples/tictactoe/tictactoe.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/dataCollection.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/inputField.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/textArea.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
www/src/pages/headless/radioGroup.md
www/src/pages/headless/tabGroup.md
www/src/pages/headless/toast.md

This PR adds a new `joinClasses` function to replace the current `classes` function in order to minimize naming confusion.
The `classes` function gets deprecated.
The current name was meant to be short, but as it seems quite often it competes with parameters having the same name, which are passed in from higher call sites. This might look confusing:
```kotlin
classes(classes, "... some local added classes", ...)
```
Use the added `joinClasses` function over the now deprecated `classes` function. This can be done automatically via IntelliJ.
Ideally, optimize your imports after replacing the respective calls.
Closes #828

Rename `classes` utility function to `joinClasses` in order to reduce naming confusion

---

core/src/jsMain/kotlin/dev/fritz2/core/events.kt
core/src/jsMain/kotlin/dev/fritz2/core/listener.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/events.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/toast.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
www/src/pages/docs/30_Render HTML.md
www/src/pages/docs/45_EventHandling.md

fritz2 has supported event-handling since its beginning, but with the [release of RC1](https://github.com/jwstegemann/fritz2/releases/tag/v1.0-RC1), we introduced dedicated handling for the internal DOM-API event manipulation with `stopPropagation`, `stopImmediatePropagation` or `preventDefault` (see also PR #585). These were part of the `Listener`-class and implemented as kind of `builder`-pattern to provide a fluent API:
```kotlin
keydowns.stopPropagagtion().preventDefault().map { ... } handledBy someHandler
//       ^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^      ^^^^^
//       each call returns `Listener` with        "normal" flow-transformation
//       modified event state.
```
Those three functions were also provided with extensions on `Flow<T>`  in order to make them callable, like shown …

Repairs event handling with focus of manipulation and filtering

---

core/src/jsMain/kotlin/dev/fritz2/core/foundation.kt
core/src/jsMain/kotlin/dev/fritz2/core/transitions.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/disclosure.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
www/src/pages/headless/disclosure.md

This PR changes the headless disclosure to only render its panel's content once and then show/hide it based on styling. Currently, the panel's content is rendered every time the disclosure is opened/closed. 
> [!WARNING] 
> In order to achieve this, the headless component no longer controls the panel's visibility. All styling is now solely done by the implementor of a headless discloure and needs to be adjusted accordingly. Thus, the changes introduced in this PR are _api breaking_!
Additionally, the `transition` function for `Flow`-based transitions has been extended to allow optional control over initial classes and classes that should be present after the leave-transition has ended. This is useful to allow transitions on an element's visibility which are normally not possible using …

Improve disclosure component for state creating content, add options to control a transition's initial and after-end classes

---

headless-demo/tests/components/modal.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/focus.kt

When using the `trapFocusWhenever` in some rare situations, the focus-trap would remain alive after closing the trap-container. This bug is now closed.
This was reproducible inside the `PopOver`-component (in the demo!): After closing the popover one could no more *tab* away from the button.
Also the focus-trap is now located correctly inside the `PopOver`-component: On top of the portal-container and not the trigger.

This PR fixes some Flow-based focus-trap issue

---

.github/workflows/build.yml
core/src/jsMain/kotlin/dev/fritz2/remote/http.kt
core/src/jsTest/kotlin/dev/fritz2/remote/http.kt

This PR fixes two build issues that recently occurred in our project.
The above mentioned task has been deprecated and its use now causes pipelines to fail.
As a fix, this PR updates the version to consistently be `v4`, as recommended in the [deprecation notice](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/).
Fixes the failing `testBasicAuth` test in the `http.kt` test file.
The failing test was caused by a change of behavior in Chrome headless, displaying an authentication popup when a 401 status was received from a basic auth endpoint.
The popup cannot be dismissed by our test and causes the respective test to fail, even though all assertions are correct.
As a result, the easies fix is to remove the problematic test case.

Fixes recent build issues

---

.github/workflows/libs.yml

This fix is necessary due to the deprecation described in PR #881 / commit 446d339ae58f586ed6213707633d2b5713aafb0e and was previously overseen.

Upgrades publishing pipeline `upload-artifact` task to v4

---

core/api/core.api
core/src/commonMain/kotlin/dev/fritz2/core/flows.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/disclosure.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt

This PR resolves various minor issues:
Closes #753
Closes #867
As the extension functions remain in the same package, this change should practically always be non be api-breaking.
Closes #873

Resolves various minor issues

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
headless-demo/tests/components/combobox.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
www/src/pages/headless/combobox.md

This PR adds a headless `combobox` component inspired by the [HeadlessUI Combobox](https://headlessui.com/react/combobox).
The component can be created via the `combobox` factory.
For the full documentation visit the [online documentation](https://www.fritz2.dev/headless/combobox/).  
_During the review phase the documentation needs to be accessed through the locally running 11ty page, of course_.
API-sketch:
```kotlin
combobox<T> {
val items: ItemsHook()
// params: List<T> / Flow<List<T>>
var itemFormat: (T) -> String
val value: DatabindingProperty<T>
var filterBy: FilterFunctionProperty
// params: (Sequence<T>, String) -> Sequence<T> / T.() -> String
val selectionStrategy: SelectionStrategyProperty
// methods: autoSelectMatches() / manual()
var maximumDisplayedItems: Int = 20
var …
```

Adds a headless `combobox` component

---

core/src/jsMain/kotlin/dev/fritz2/core/events.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt

This PR adds the following missing events in its listener definitions according to this [list](https://www.w3schools.com/jsref/dom_obj_event.asp):
- animationend
- animationiteration
- animationstart
- error
- transitionend
fix #877

Add missing events

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
headless-demo/tests/components/combobox.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
www/src/pages/headless/combobox.md

This PR fixes the handling of `null` values in the headless combobox's data-binding.
Now, when a `null` value is received, both the input and internal values are properly reset.

Improves handling of null values in the headless combobox

---

headless-demo/src/commonMain/kotlin/dev/fritz2/headlessdemo/components/ComboboxDemoConfig.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
headless-demo/tests/components/combobox.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
www/src/pages/headless/combobox.md

This PR implements various smaller improvements for the headless combobox.
Check out the linked individual commits below to see the changes in smaller, more concise diffs:
- [Adds a hook to control whether the combobox's dropdown opens lazily or eagerly](https://github.com/jwstegemann/fritz2/commit/b9c255c421f3b371fcb116a30665b8995eb3f568)
- i.e.: When the user starts typing vs as soon as the user focuses the input
- [Reduces flickering when re-opening a combobox](https://github.com/jwstegemann/fritz2/commit/67eff8eb0b0dc625ae79401135d36850759c9c63)
- [Adds missing documentation regarding the combobox's selection mode](https://github.com/jwstegemann/fritz2/pull/891/commits/df743f50945a48b23335520e2d612838e545066c)

Implements various smaller combobox improvements

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/portalling.kt

The combination of a trigger inside some reactive scope and a headless modal would lead to corrupt application state before this fix.
Due to the natur of portalling, portalled portions of components are not automatically coupled to the reactive rendering of fritz2's mountpoint-concept. The portal-root container resides out of its scope.
That is why we forward the scope to each portal-container and could use the latter to register some lifecycle-hooks in order to remove obsolete portals based upon the re-rendering happening inside fritz2's main `RenderContext`.
As modals do not have any relation to its trigger(s) and do not reside inside the same mount-point, they were not coupled to the trigger-flow and its cancellation.
This is now fixed!
If the trigger is removed due to some reactive …

Fixes some bug with modals and reactive renderings

---

headless-demo/tests/components/combobox.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt

This PR fixes a bug in the headless combobox component where parts of the input are deleted/reset when the user types fast and the rendering is slow.
Additionally, a few compiler warnings introduced with the Kotlin 2.0 upgrade are resolved.

Fixes the combobox deleting input when the rendering is slow

---

core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/tags.kt

The pimped `className`-function (introduced by PR #823 in `1.0-RC15` release) did not apply exception handling. That could lead to errors, if there is code that removes some element:
The independent reactive renderings could simply lead to corner cases, where a lens will try to access its mapped object (e.g. by `mapByElement`) that is no longer part of the stored model. So a
`CollectionLensGetException` will be thrown and must be handled by the consuming code.
This PR adds such exception handling code and a unit test to verify the new, correct behaviour.

Fixes some potential bug with mapping lenses

---

core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt
core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
core/src/jsTest/kotlin/dev/fritz2/core/tags.kt

Improves the API doc for `renderIf`

Improves the API doc for `renderIf`

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt

This PR adjusts the combobox's data-binding to only accept values that are different from the previous selection.
In most cases, this should make no difference. There are corner cases, however, where the value is quickly updated multiple times in a row, causing the internals to run into race-conditions.
Fixes #912

Combobox: Only accept distinct values via data-binding

---

headless-demo/src/commonMain/kotlin/dev/fritz2/headlessdemo/components/ComboboxDemoConfig.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
www/src/pages/headless/combobox.md

This PR unifies the naming of one of the `selectionStrategy` options in the `combobox` to` autoSelectMatch`. I noticed that the Fritz2 documentation referred to this strategy as `autoSelectMatches`, which is incorrect. To prevent future inconsistencies, I decided to standardize the terminology across the entire project.

Standardizes the combobox selectionStrategy name to autoSelectMatch

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/popOver.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt

This PR allows event propagation of headless component toggles.
In some headless component toggles, events were explicitly filtered by calling `stopPropagation()` and `preventDefault()` on their click events.
This caused issues when multiple overlay-components are open at the same time as overlays would not close automatically when another toggle has been clicked.
Removing the above calls enables the implementor to choose the right event handling strategy for their component but also fixes the described issues.
See https://github.com/jwstegemann/fritz2/commit/1358563c8ef5c90a15a6dd070677bb4243eb32c5
---
Additionally, a bug in the headless popOver demo is fixed where the dropdown would immediately be closed when the toggle's button was clicked.
See …

Allows event propagation of headless component toggles, fixes headless popover demo

---

www/src/pages/docs/45_EventHandling.md

Fixes minor mistake in `stopImmediatePropagation`-example of the Event Handling documenation

Fixes minor mistake in Event Handling documentation

---

www/package-lock.json
www/package.json

This PR updates 11ty to version 3.0.0 and also bumps its dependencies to the latest compatible versions.
As a result the styling is no longer broken and the security warnings emerging from the outdated dependencies are resolved as well.
Closes #864 
Closes #903

Updates 11ty to version 3.0.0

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/Combobox.kt

Currently the ComboBox dismissed an initial value. This is now fixed.
Remark: There is no test yet, that would test this behaviour. We need to extend our demo app to make this possible. We need another, dedicated issue for that.

Fix setting an initial value for the ComboBox

---

headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/App.kt
headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/Combobox.kt
headless-demo/tests/components/combobox.spec.ts
headless/src/jsMain/kotlin/dev/fritz2/headless/components/Combobox.kt

This PR simplifies the combobox's internal state handling in order to fix an issue related to its open-state and make it more robust in general:
- The open state of the combobox is no longer managed inside the component itself but instead fully controlled by the `OpenClose` mixin, making it more robust
- A regression test for an issue resulting in infinite opening and closing of the dropdown is added
- The component demo is restructured to allow more complex testing in the future: It is now split in two parts - the public demo and internal test drives. Some parts of the demo are moved from the public example to the internal testdrive.

Simply the combobox's internal state handling of the open-state

---

headless-demo/package-lock.json
headless-demo/package.json

This PR updates Playwright to the above version.
This change is not only for maintenance but also needed since the previous version (1.40.1) fails to install on the latest version of Ubuntu, which our GitHub Actions runners are using.
Once merged, this PR should fix the build errors of #928 and #929.
See [this](https://github.com/microsoft/playwright/issues/33051) issue for more information.

Updates Playwright to version 1.49.1

---

core/api/core.api
core/src/commonMain/kotlin/dev/fritz2/core/Inspector.kt
core/src/commonMain/kotlin/dev/fritz2/core/Lens.kt
core/src/commonTest/kotlin/dev/fritz2/core/Lens.kt
core/src/jsMain/kotlin/dev/fritz2/core/SubStores.kt
www/src/pages/docs/50_StoreMapping.md

This PR adds a `mapNullable` function to `Store`s and `Inspector`s that works as the reverse equivalent for `mapNull`.
The function can be used to map _non-nullable_ Stores/Inspectors to _nullable_ ones as follows:
```kotlin
val nonNullableStore: Store<String> = storeOf("")
val nullableStore: Store<String?> = 
nonNullableStore.mapNullable(placeholder = "Unknown")
//                               ^^^^^^^^^^^^^^^^^^^^^^^
//                               When the parent has the specified placeholder value,
//                               the mapped Store will have `null` as its value.
```
Closes #927

Add `mapNullable` function to `Store`s and `Inspector`s

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/Switch.kt

The `click`-event is now correctly handled by stop propagating it and `preventDefault` as the headless component will do all the work.
This could have led to bugs when using the component with explicit `DataBinging`, where the `handler`-lambda would be used to intercept the update call.

Fixes a small potential bug on headless switch component

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/Switch.kt

This reverts commit b20fd4d55d8ce9724370d57f68b6d883423ea908 which is essentially PR #933.
The fix was incorrect!

Revert "Fixes a small potential bug on headless switch component (#933)"

---

headless/src/jsMain/kotlin/dev/fritz2/headless/components/Combobox.kt

This PR adds a missing `stopPropagation` call in the combobox's keyboard event handling in order to prevent those events from bubbling to other elements.

Stop propagation of combobox keyboard events
